### PR TITLE
Optimization: New escape_str function for sanitizing strings

### LINKED ISSUE #641: clean function for escaping control characters in a string and truncating it
When we log an exception from a contract, we want to remove any new lines put in by the contract writer and limit the size of the message. As suggested in the review of eosnetworkfoundation/mandel#733, use of `fc::format_string` is inefficient; a general purpose `clean` method that optionally escapes control characters (specifically newline) and truncates can be created for such a purpose.

This is a transfer of eosnetworkfoundation/mandel#803 originally entered by @linh2931, it is being moved to `leap` for easier visibility.

### PR DESCRIPTION
**Pull request by heifner**
Create a new `escape_str` function for use of sanitizing strings without having to use `format_string` with its overhead of `mutable_variant_object`.
Also optimize `print_debug` used for contract console output.

Resolves #641

### CODE REVIEW

File: libraries/chain/apply_context.cpp [hunk 1]
```diff
@@ -19,15 +19,26 @@ namespace eosio { namespace chain {
...
+         prefix += "\n[(";
+         prefix += ar.act.account.to_string();
+         prefix += ",";
+         prefix += ar.act.name.to_string();
+         prefix += ")->";
+         prefix += receiver.to_string();
+         prefix += "]";
+
+         std::string output;
+         output.reserve(512);
```
Comment (linh2931) [inline libraries/chain/apply_context.cpp:34]: We didn't have this 512 limit before the change.

File: plugins/producer_plugin/producer_plugin.cpp [hunk 2]
```diff
@@ -2085,23 +2085,22 @@ inline std::string get_detailed_contract_except_info(const packed_transaction_pt
...
       act_name = actions[0].name.to_string();
    }
 
-   details = except_ptr ? except_ptr->top_message() : (trace && trace->except) ? trace->except->top_message() : std::string();
-   if (!details.empty()) {
-      details = fc::format_string("${d}", fc::mutable_variant_object() ("d", details), true);  // true for limiting the formatted string size
-   }
+   std::string details = except_ptr ? except_ptr->top_message()
+                                    : (trace && trace->except) ? trace->except->top_message()
+                                                               : std::string();
```
Comment (greg7mdp) [inline plugins/producer_plugin/producer_plugin.cpp:2101]: Maybe parenthesize so precedence is clear
```suggestion
   std::string details = except_ptr ? except_ptr->top_message()
                                    : ((trace && trace->except) ? trace->except->top_message()
                                                               : std::string());
```

Comment (heifner) [reply plugins/producer_plugin/producer_plugin.cpp]: Done.

File: libraries/libfc/src/string.cpp [hunk 3]
```diff
@@ -83,13 +85,42 @@ namespace fc  {
...
       return boost::algorithm::trim_copy(s);
-      /*
-      std::string cpy(s);
-      boost::algorithm::trim(cpy);
-      return cpy;
-      */
   }
 
+  std::pair<std::string&, bool> escape_str( std::string& str, bool escape_control_chars,
+                                            std::size_t max_len, const char* add_truncate_str )
```
Comment (greg7mdp) [inline libraries/libfc/src/string.cpp:91]: A suggestion only:

```suggestion
  enum class escape_control_chars { off, on };
  std::pair<std::string&, bool> escape_str( std::string& str, escape_control_chars escape_ctrl,
                                            std::size_t max_len, const char* add_truncate_str )
```

Which allows you to call it as:

`fc::escape_str(details, fc::escape_control_chars::on, 1024);`

which is nicer than having to declare a bool for clarity.

File: libraries/libfc/src/string.cpp [hunk 4]
```diff
@@ -83,13 +85,42 @@ namespace fc  {
...
+     if (itr != str.end() || !fc::is_valid_utf8( str )) {
+        str = escape_string(str, nullptr, escape_control_chars);
+        modified = true;
+        if (str.size() > max_len) {
+           str.resize(max_len);
+           truncated = true;
+        }
+     }
+
+     if (truncated && add_truncate_str != nullptr ) {
```
Comment (linh2931) [inline libraries/libfc/src/string.cpp:116]: Just a style preference. `add_truncate_str != nullptr` can just be `add_truncate_str`.

File: libraries/libfc/include/fc/string.hpp [hunk 5]
```diff
@@ -20,4 +21,22 @@ namespace fc
   class variant_object;
   std::string format_string( const std::string&, const variant_object&, bool minimize = false );
   std::string trim( const std::string& );
+
+  /**
+   * Convert '\t', '\r', '\n', '\\' and '"'  to "\t\r\n\\\"" if escape_control_chars == true
```
Comment (linh2931) [inline libraries/libfc/include/fc/string.hpp:26]: Should "\t\r\n\\\"" be "\\t\\r\\n\\\\"?

File: libraries/chain/apply_context.cpp (hunk 1 above)
Comment (heifner) [reply libraries/chain/apply_context.cpp:34]: This is not a limit, but a hint on memory allocation.

File: libraries/libfc/src/string.cpp (hunk 4 above)
Comment (heifner) [reply libraries/libfc/src/string.cpp:116]: I very much prefer the style of explicit `!= nullptr`.

File: libraries/libfc/src/string.cpp [hunk 6]
```diff
@@ -83,13 +85,42 @@ namespace fc  {
...
+     bool modified = false, truncated = false;
+     // truncate early to speed up escape
+     if (str.size() > max_len) {
+        str.resize(max_len);
+        modified = truncated = true;
+     }
+     auto itr = escape_control_chars
+           ? std::find_if(str.begin(), str.end(),
+                          [](const auto& c) {
+              return c == '\x7f' || c == '\\' || c == '\"' ||  (c >= '\x00' && c <= '\x1f'); } )
```
Comment (greg7mdp) [inline libraries/libfc/src/string.cpp:102]: Isn't `c >= '\x00'` always true?

File: libraries/libfc/src/string.cpp [hunk 7]
```diff
@@ -83,13 +85,42 @@ namespace fc  {
...
+           : std::find_if(str.begin(), str.end(),
+                          [](const auto& c) {               // x09 = \t, x0a = \n,                   x0d = \r
+              return c == '\x7f' || (c >= '\x00' && c <= '\x08') || c == '\x0b' || c == '\x0c' || (c >= '\x0e' && c <= '\x1f'); } );
```
Comment (greg7mdp) [inline libraries/libfc/src/string.cpp:105]:
```suggestion
              return c == '\x7f' || (c <= '\x1f' && c != '\t' && c != '\n' && c != '\r'); } );
```

File: libraries/libfc/src/string.cpp (hunk 6 above)
Comment (heifner) [reply libraries/libfc/src/string.cpp:102]: No `c` (char) is signed.

Comment (greg7mdp) [reply libraries/libfc/src/string.cpp:102]: OK, still in the case that `char` is signed, and that we have some negative ones, then your version does preserve the previous behavior.

File: libraries/libfc/src/string.cpp (hunk 4 above)
Comment (linh2931) [reply libraries/libfc/src/string.cpp:116]: ok.

File: libraries/chain/apply_context.cpp (hunk 1 above)
Comment (linh2931) [reply libraries/chain/apply_context.cpp:34]: oha,

File: libraries/libfc/src/string.cpp (hunk 3 above)
Comment (heifner) [reply libraries/libfc/src/string.cpp]: Done.

File: libraries/libfc/include/fc/string.hpp (hunk 5 above)
Comment (linh2931) [reply libraries/libfc/include/fc/string.hpp:26]: Github automatically re-formatted two `\\t` into one `\t` above. In the test, `\t` becomes `\\t`.

Comment (heifner) [reply libraries/libfc/include/fc/string.hpp:26]: Ah, so you think the comment should be:
```
Convert '\t', '\r', '\n', '\\' and '"'  to "\\t\\r\\n\\\\\"" if escape_ctrl == on
```
?

File: libraries/libfc/src/string.cpp [hunk 8]
```diff
@@ -83,13 +85,42 @@ namespace fc  {
...
       return boost::algorithm::trim_copy(s);
-      /*
-      std::string cpy(s);
-      boost::algorithm::trim(cpy);
-      return cpy;
-      */
   }
 
+  std::pair<std::string&, bool> escape_str( std::string& str, escape_control_chars escape_ctrl,
+                                            std::size_t max_len, const char* add_truncate_str )
```
Comment (greg7mdp) [inline libraries/libfc/src/string.cpp:91]: I think the more modern version for the last parameter would be to be  be a `std::string_view` instead of a raw pointer.

File: libraries/libfc/include/fc/string.hpp (hunk 5 above)
Comment (heifner) [reply libraries/libfc/include/fc/string.hpp:26]: I guess I read the comment as saying that is what the output would look like, not what its internal representation in the string would be.

File: libraries/libfc/src/string.cpp (hunk 8 above)
Comment (heifner) [reply libraries/libfc/src/string.cpp]: Done.

**Review by greg7mdp — APPROVED** [review]

File: libraries/libfc/src/string.cpp [hunk 9]
```diff
@@ -83,13 +85,42 @@ namespace fc  {
...
+     if (itr != str.end() || !fc::is_valid_utf8( str )) {
+        str = escape_string(str, nullptr, escape_ctrl == escape_control_chars::on);
+        modified = true;
+        if (str.size() > max_len) {
+           str.resize(max_len);
+           truncated = true;
+        }
+     }
+
+     if (truncated && !add_truncate_str.empty()) {
```
Comment (greg7mdp) [inline libraries/libfc/src/string.cpp:116]:
```suggestion
     if (truncated) {
```

Comment (heifner) [reply libraries/libfc/src/string.cpp:116]: I thought about that, but the impl of `string.append()` would make additional `if` checks not needed.

Comment (heifner) [reply libraries/libfc/src/string.cpp:116]: oh, but will almost never be empty(), I'll remove the check.

Comment (greg7mdp) [reply libraries/libfc/src/string.cpp]: [operator+=](https://en.cppreference.com/w/cpp/string/basic_string/operator%2B%3D) has a version that takes a StringViewLike, so the test would de done there instread of in the `if` before. I'm not seeing any drawback.

Comment (heifner) [reply libraries/libfc/src/string.cpp]: The impl of the `operator+=` that takes a `string_view` does:
`append(sv.data(), sv.size())` and then it checks `if (size)` in the impl of `append`. Regardless, I agree and have removed the check.

**Review by greg7mdp — APPROVED** [review]
