### PR TITLE
[3.2] Backport SHiP fixes from eosio/eos release/2.2.x

### LINKED ISSUE #592: 3.2 state_history_plugin crashes under heavy load
[Information reported by community]

3.1 does not have this issue. Observed with both v3.2.0-rc1 and v3.2.0.

Reproducible by indexing with Hyperion with high scale values.

image

Double these values to speed up the indexing and will reproduce the state_history_plugin crash.

image

```
OC enabled:
##############
info  2022-12-13T16:24:31.615 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.620 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.622 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.625 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.627 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.628 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.629 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.632 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.632 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.632 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.633 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.634 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.636 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.636 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.638 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
double free or corruption (out)
ERROR: EOS VM OC compiler monitor exiting with active sessions


info  2022-12-13T17:11:18.060 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.062 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.068 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.068 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.068 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.069 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.069 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
Provided index out of range for variant.
    {}
    nodeos  static_variant.hpp:19 from_index
Error unpacking field trx
    {"field":"trx"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::transaction_receipt
    {"type":"eosio::chain::transaction_receipt"}
    nodeos  raw.hpp:668 unpack
Error unpacking field transactions
    {"field":"transactions"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack

warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
Provided index out of range for variant.
    {}
    nodeos  static_variant.hpp:19 from_index
Error unpacking field _storage
    {"field":"_storage"}
    nodeos  raw.hpp:363 operator()
error unpacking fc::crypto::signature
    {"type":"fc::crypto::signature"}
    nodeos  raw.hpp:668 unpack
Error unpacking field signatures
    {"field":"signatures"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::packed_transaction
    {"type":"eosio::chain::packed_transaction"}
    nodeos  raw.hpp:668 unpack
Error unpacking field trx
    {"field":"trx"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::transaction_receipt
    {"type":"eosio::chain::transaction_receipt"}
    nodeos  raw.hpp:668 unpack
Error unpacking field transactions
    {"field":"transactions"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack

info  2022-12-13T17:11:18.070 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
(b & ~1) == 0:
    {}
    nodeos  raw.hpp:334 unpack
optional<eosio::chain::legacy::producer_schedule_type>
    {"type":"eosio::chain::legacy::producer_schedule_type"}
    nodeos  raw.hpp:282 unpack
Error unpacking field new_producers
    {"field":"new_producers"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack

warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
Provided index out of range for variant.
    {}
    nodeos  static_variant.hpp:19 from_index
Error unpacking field trx
    {"field":"trx"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::transaction_receipt
    {"type":"eosio::chain::transaction_receipt"}
    nodeos  raw.hpp:668 unpack
Error unpacking field transactions
    {"field":"transactions"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack


OC disabled
#############
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.087 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.094 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.095 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.095 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.106 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.106 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.108 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.116 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.119 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.123 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.123 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.124 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.135 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.142 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.143 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.144 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
double free or corruption (out)
```

### LINKED ISSUE #593: state_history_plugin unused code
`libraries/state_history/include/eosio/state_history/log.hpp` `state_history_log` The internal thread is not used.

```
   std::thread                                                              thr;
   std::atomic<bool>                                                        write_thread_has_exception = false;
   std::exception_ptr                                                       eptr;
   boost::asio::io_context                                                  ctx;
   boost::asio::io_context::strand                                          work_strand{ctx};
   boost::asio::executor_work_guard<boost::asio::io_context::executor_type> work_guard =
       boost::asio::make_work_guard(ctx);
   std::recursive_mutex                                                     mx;
```
The `thr` and `ctx` is not used for anything after creation. The `mx` is not protecting anything that needs protection.

### PR DESCRIPTION
**Pull request by heifner**
Backport of `state_history_plugin` fixes: https://github.com/EOSIO/eos/pull/10608

From the backport:
- Create an additional thread for all ship network communication. This thread already existed in release/3.2 but was not used. See https://github.com/AntelopeIO/leap/issues/593.
- Fix bug where state history plugin would send blocks with block_num smaller than the client requests when the state history block head is behind the block head of the client.

Additional changes:
- Remove `session_manager_t` and use post to main thread so `session_set` is only accessed from main thread.
- Use `named_thread_pool` to simplify SHiP thread. Older versions of boost do not provide an `acceptor` that takes a `strand` in constructor, so rely on implicit strand of single thread running `io_context` which is much simpler than wrapping all calls in `boost::asio::bind_executor`.
- Made sure the destructor of boost beast web socket stream is called on the SHiP thread. The session tests in #628 would consistently crash in the the stream destructor when destroyed on the wrong thread.

Reproduced the crash of #592. After this PR, was unable to reproduce #592 crash. 

This PR does not include `accept` `too_many_files_open` fix: #603 
#577 has some of these changes already but takes a slightly different approach. I've updated #577 with the thread separation changes of this PR, see #628.

Resolves #592

### CODE REVIEW

File: plugins/state_history_plugin/state_history_plugin.cpp [hunk 1]
```diff
@@ -190,39 +193,33 @@ struct state_history_plugin_impl : std::enable_shared_from_this<state_history_pl
...
-          boost::asio::post(this->plugin->work_strand, [self = this->shared_from_this(), str = s ]() {
-            self->send_queue.push_back({str, str + strlen(str)});
-            self->send();
-         });
-      }
-
       template <typename T>
       void send(T obj) {
-         boost::asio::post(this->plugin->work_strand, [self = this->shared_from_this(), obj = std::move(obj) ]() {
+         boost::asio::post(this->plugin->thread_pool.get_executor(), [self = this->shared_from_this(), obj = std::move(obj) ]() mutable {
```
Comment (spoonincode) [inline plugins/state_history_plugin/state_history_plugin.cpp:215]: It's okay to lose the FIFO ordering here right? Initial look seems okay, except maybe for a pathological case: if a flood of `get_status_request_v0` are sent in, some of the responses may be sent out of order.

File: plugins/state_history_plugin/state_history_plugin.cpp [hunk 2]
```diff
@@ -87,11 +87,7 @@ struct state_history_plugin_impl : std::enable_shared_from_this<state_history_pl
    using acceptor_type = std::variant<std::unique_ptr<tcp::acceptor>, std::unique_ptr<unixs::acceptor>>;
    std::set<acceptor_type>          acceptors;
 
-   std::thread                                                              thr;
-   boost::asio::io_context                                                  ctx;
-   boost::asio::io_context::strand                                          work_strand{ctx};
-   boost::asio::executor_work_guard<boost::asio::io_context::executor_type> work_guard =
-       boost::asio::make_work_guard(ctx);
+   named_thread_pool                thread_pool{"SHiP", 1}; // use of executor assumes only one thread
```
Comment (linh2931) [inline plugins/state_history_plugin/state_history_plugin.cpp:90]: Do we want to be able to configure the number of SHiP threads?

Comment (heifner) [reply plugins/state_history_plugin/state_history_plugin.cpp:90]: If we increase from 1 then we need to create and use a strand for each connection. I'm open to doing that if desired. I have a nice manual test setup for testing high threading if that is something we want to do now. @spoonincode thoughts?

Comment (spoonincode) [reply plugins/state_history_plugin/state_history_plugin.cpp:90]: I would say no. imo the code needs to be substantially cleaned up before adding any more complexity to it.

**Review by spoonincode — DISMISSED** [review]
I went through this quite a bit; it's a clear improvement and I couldn't find any obvious problems. But certain aspects are tricky to reason through, especially because I would consider them at opposite to typical asio patterns. We need to get 3.2 in better shape so makes sense to go with this now, but I'd really like to see this cleaned up a _lot_ more in the future. I've added #627 to capture that.

**Review by linh2931 — APPROVED** [review]

File: plugins/state_history_plugin/state_history_plugin.cpp [hunk 3]
```diff
@@ -693,7 +698,6 @@ void state_history_plugin::plugin_startup() {
    handle_sighup(); // setup logging
 
    try {
-      my->thr = std::thread([ptr = my.get()] { ptr->ctx.run(); });
       my->listen();
```
Comment (heifner) [inline plugins/state_history_plugin/state_history_plugin.cpp:701]: Seems like `listen()` should be posted to the ship thread.

Comment (heifner) [reply plugins/state_history_plugin/state_history_plugin.cpp:701]: If we do post `listen()` to the ship thread, we need either https://github.com/AntelopeIO/leap/pull/632 or something specific only for this use.

Comment (spoonincode) [reply plugins/state_history_plugin/state_history_plugin.cpp:701]: It's too bad you can't just start the thread after calling `my->listen()`. That seems like a rather unfortunate behavior of `named_thread_pool` that it blocks that usage pattern.

Comment (heifner) [reply plugins/state_history_plugin/state_history_plugin.cpp:701]: I don't follow. How would that make any difference?

Comment (heifner) [reply plugins/state_history_plugin/state_history_plugin.cpp:701]: I see what you mean. I find it easier to reason about the exclusivity by posting it to the ship thread. I agree it is nice to acquire resources in startup as it simplifies error handling and error reporting. 

For this PR, I modified `named_thread_pool` to allow for delay start of the threads and changed to start the thread after the call to `listen()`.

I would like to get https://github.com/AntelopeIO/leap/pull/632 into `main` along with this PRs delay start of `named_thread_pool`.

**Review by spoonincode — APPROVED** [review]

File: libraries/chain/thread_utils.cpp [hunk 4]
```diff
@@ -1,35 +1,42 @@
...
-
 void named_thread_pool::stop() {
    _ioc_work.reset();
    _ioc.stop();
-   _thread_pool.join();
-   _thread_pool.stop();
+   for( auto& t : _thread_pool ) {
+      t.join();
+   }
+   _thread_pool.clear();
```
Comment (linh2931) [inline libraries/chain/thread_utils.cpp:40]: Should those actions be done in the reverse order of `start()`?

Comment (heifner) [reply libraries/chain/thread_utils.cpp:40]: The order looks correct to me.

Comment (spoonincode) [reply libraries/chain/thread_utils.cpp:40]: Though possibly you don't actually need to create & destroy the work guard across start/stops like this.

Comment (heifner) [reply libraries/chain/thread_utils.cpp:40]: Yeah, maybe, but seems safer to do so.

Comment (linh2931) [reply libraries/chain/thread_utils.cpp:40]: I meant should `_ioc_work.reset();` be done last?

Comment (spoonincode) [reply libraries/chain/thread_utils.cpp:40]: It shouldn't really matter, other then it needs to be destroyed before the io_context is destroyed. afaict don't really even need to do the `.reset()` since the class members will be dtored in appropriate order.

Comment (spoonincode) [reply libraries/chain/thread_utils.cpp:40]: that's why not making it optional is kinda nice, you can just make the class:
```c++
      boost::asio::io_context        _ioc;
      ioc_work_t      _ioc_work{_ioc);
```
and just not touch it at all.

Comment (spoonincode) [reply libraries/chain/thread_utils.cpp:40]: (but I don't think it's something that requires changing)

Comment (heifner) [reply libraries/chain/thread_utils.cpp:40]: Good point. All the current impl of ioc_work does is call `stop()`.

**Review by linh2931 — APPROVED** [review]
