### PR TITLE
[3.2] Modify trace_api_plugin to report serialization errors to user

### LINKED ISSUE #1433: trace_api_plugin reports block trace missing when http-max-response-time-ms limit is reached
`{"code":404,"message":"Trace API: block trace missing","error":{"code":0,"name":"","what":"","details":[]}}`

https://github.com/AntelopeIO/leap/blob/v4.0.4/plugins/trace_api_plugin/abi_data_handler.cpp#L40 Calls `except_handler` when `yield()` throw exception and returns `{}`. The `except_handler` is setup to https://github.com/AntelopeIO/leap/blob/v4.0.4/plugins/trace_api_plugin/trace_api_plugin.cpp#L204 only log the error. This means a small `http-max-response-time-ms` causes `trace_api_plugin` to indicate it could not find the block rather than a deadline exception was hit.

### PR DESCRIPTION
**Pull request by heifner**
The exception handler for the `trace_api_plugin` data handler now rethrows any exceptions so they can be reported to the API caller of `/v1/trace_api/get_block` and `/v1/trace_api/get_transaction_trace`.

`trace_api_plugin` will now report
```
./cleos --verbose --print-response get block_trace 20
RESPONSE:
---------------------
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 2,
    "name": "timeout_exception",
    "what": "deadline 2023-07-25T20:19:49.442 exceeded by 24us ",
    "details": [{
        "message": "deadline 2023-07-25T20:19:49.442 exceeded by 24us ",
        "file": "trace_api_plugin.cpp",
        "line_number": 288,
        "method": "operator()"
      }
    ]
  }
}
---------------------
error 2023-07-25T20:19:49.445 cleos     main.cpp:4498                 operator()           ] Failed with error: 2 timeout_exception: deadline 2023-07-25T20:19:49.442 exceeded by 24us
deadline 2023-07-25T20:19:49.442 exceeded by 24us
    {}
    cleos  trace_api_plugin.cpp:288 operator()
```
Instead of:
```
./cleos --verbose --print-response get block_trace 20
RESPONSE:
---------------------
{
  "code": 404,
  "message": "Trace API: block trace missing",
  "error": {
    "code": 0,
    "name": "",
    "what": "",
    "details": []
  }
}
---------------------
Error 3200005: http request fail
Error Details:
Error code 404
: {"code":404,"message":"Trace API: block trace missing","error":{"code":0,"name":"","what":"","details":[]}}
```

Resolves #1433

### CODE REVIEW

**Review by dimas1185 — APPROVED** [review]

File: plugins/trace_api_plugin/test/test_data_handlers.cpp [hunk 1]
```diff
@@ -135,6 +135,52 @@ BOOST_AUTO_TEST_SUITE(abi_data_handler_tests)
...
+          ("a", 0)
+          ("b", 1)
+          ("c", 2)
+          ("d", 3);
+
+      uint32_t depth = 0;
+      BOOST_CHECK_EXCEPTION(handler.serialize_to_variant(action_trace_t, [&](){ ++depth; if (depth > 1) throw std::runtime_error("oops"); }), std::runtime_error,
+                            [](const std::runtime_error& e) {
+                               return std::string(e.what()).find("oops") != std::string::npos;
+                            });
```
Comment (greg7mdp) [inline plugins/trace_api_plugin/test/test_data_handlers.cpp:181]: Probably you should either check `except_called == true` here, or remove the variable alltogether.

Comment (greg7mdp) [reply plugins/trace_api_plugin/test/test_data_handlers.cpp:181]: PS: cool test. Did you make up the abi out of thin air?

File: tests/trace_plugin_test.py [hunk 2]
```diff
@@ -102,6 +103,19 @@ def test_TraceApi(self) :
...
         self.assertTrue(isTrxInBlockFromTraceApi)
 
+        # relaunch with no time allocated for http response & abi-serializer. Will fail because get_info fails.
+        node.kill(signal.SIGTERM)
+        Utils.Print("Ignore expected: ERROR: Node relaunch Failed")
+        isRelaunchSuccess = node.relaunch(timeout=10, addSwapFlags={"--http-max-response-time-ms": "0", "--abi-serializer-max-time-ms": "10"})
+
+        cmdDesc="get block_trace"
+        cmd=" --print-response %s %d" % (cmdDesc, blockNum)
+        cmd="%s %s %s" % (Utils.EosClientPath, node.eosClientArgs(), cmd)
```
Comment (greg7mdp) [inline tests/trace_plugin_test.py:113]: Why do it in 2 steps, and not:
` cmd="%s %s --print-response %s %d" % (Utils.EosClientPath, node.eosClientArgs(), cmdDesc, blockNum)`

**Review by greg7mdp — APPROVED** [review]

File: plugins/trace_api_plugin/test/test_data_handlers.cpp (hunk 1 above)
Comment (heifner) [reply plugins/trace_api_plugin/test/test_data_handlers.cpp:181]: Thanks. I meant to add a check for that. Added.
It was copied from another test. Originally hand-crafted.

File: tests/trace_plugin_test.py (hunk 2 above)
Comment (heifner) [reply tests/trace_plugin_test.py:113]: No reason except that it was copied from another location that builds it up similar.
