### PR TITLE
[5.0] P2P: Throttle over sync window

### LINKED ISSUE #1808: p2p_sync_throttle_test failing on pinned builds
for example,
https://github.com/AntelopeIO/leap/actions/runs/6614683795/job/17967552880

```
2023-10-23T15:28:27.271674 Unthrottled sync time: 5.059182405471802 seconds
2023-10-23T15:28:27.271731 Throttled sync time: 35.088512659072876 seconds
2023-10-23T15:28:27.271883  Test failed.
Traceback (most recent call last):
  File "/__w/leap/leap/build/tests/p2p_sync_throttle_test.py", line 228, in <module>
    assert wasThrottled, 'Throttling node never reported throttling its transmission rate'
AssertionError: Throttling node never reported throttling its transmission rate
```

### PR DESCRIPTION
**Pull request by heifner**
Instead of calculating throttle limit from time of connection establishment, calculate over the specific enqueue sync window.
See https://github.com/AntelopeIO/leap/pull/1741 for original implementation. 

Update the throttle test to use more reasonable values.

Resolves #1808

### CODE REVIEW

**Review by greg7mdp — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]

**Review by spoonincode — APPROVED** [review]

File: plugins/net_plugin/net_plugin.cpp [hunk 1]
```diff
@@ -892,6 +892,8 @@ namespace eosio {
       std::atomic<size_t>             bytes_sent{0};
       std::atomic<size_t>             block_sync_bytes_received{0};
       std::atomic<size_t>             block_sync_bytes_sent{0};
+      std::chrono::nanoseconds        block_sync_send_start{0ns};    // start of enqueue blocks
+      size_t                          block_sync_send_bytes_sent{0}; // bytes sent in this set of enqueue blocks
```
Comment (dimas1185) [inline plugins/net_plugin/net_plugin.cpp:896]: I hate to quibble over naming but `block_sync_bytes_sent` and `block_sync_send_bytes_sent` just blow my mind.
Can we rename this to something like:
`block_sync_total_bytes_sent`
`block_sync_frame_bytes_sent` ?

File: plugins/net_plugin/net_plugin.cpp [hunk 2]
```diff
@@ -1740,25 +1745,38 @@ namespace eosio {
...
-            auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(get_time() - connection_start_time);
-            auto current_rate = double(block_sync_bytes_sent) / elapsed.count();
+         if (block_sync_send_start == 0ns) { // start of enqueue blocks
+            block_sync_send_start = get_time();
+            block_sync_send_bytes_sent = 0;
+         }
+         if( block_sync_rate_limit > 0 && block_sync_send_bytes_sent > 0 && peer_syncing_from_us ) {
+            auto now = get_time();
+            auto elapsed_us = std::chrono::duration_cast<std::chrono::microseconds>(now - block_sync_send_start);
+            double current_rate = (double(block_sync_bytes_sent) / elapsed_us.count()) * 100000;
```
Comment (dimas1185) [inline plugins/net_plugin/net_plugin.cpp:1755]: If you are changing variables names from my comment above, please make this line a bit more readable by renaming `current_rate` to  `current_rate_sec` or something like that. it will make it obvious that these are seconds and why you divide by `100'000`. This is optional in case you are changing the code.

**Review by dimas1185 — APPROVED** [review]
