### PR TITLE
IF: Update signature-provider parsing for base64 BLS public keys

### LINKED ISSUE #2060: IF: signature-provider for BLS keys
Currently `signature-provider` for BLS keys are specified as:
```
--signature-provider PUB_BLS_PAD80INyOVD3K0KJdl/7b5+UQGT0nrr8MDxO0tB80HMmaQS+X8YWRrYyyb7slAYFbOV69KN/skAFJfIFgdEEvD00MNhyaSJaJ1NGJjdKfq+OARJKoMBoBvj5/78n6BgLDpoJ7A===KEY:PVT_BLS_cvOsv1fAUDVgcK/J1j3U1DfQWMrmSFZDMiu4E0yJCEDWWZl3
```
The separator between the public key and private key is `=KEY:`. This can cause confusion since the base64 encoded public key also often ends in `=`.  This follows the current separator between EOS keys:
```
--signature-provider EOS5VLjLL9nY5b2QymL8QVpwRnUDEhaedeHvVJ4vU8tpaEbxAwDc3=KEY:5JpgeNa7fAf4mXukVHmnNPqcN7qHbrp4NkMJQp32c1MbrLLdwYz
```
Consider a different separator for BLS keys provided to `signature-provider`.

Also the current implementation finds the first `=` and uses it to separate out the public key from the private key. This is clearly wrong for base64 encoded keys.
https://github.com/AntelopeIO/leap/blob/hotstuff_integration/plugins/signature_provider_plugin/signature_provider_plugin.cpp#L43

If the existing separator of `=KEY:` is maintained the parsing needs to be fixed.

Currently malformed signature-provider specifications do not stop nodeos. It ignores the error and continues. Seems this should stop nodeos from starting.
```
error 2024-01-09T22:46:19.780 nodeos    producer_plugin.cpp:1143      plugin_initialize    ] Malformed signature provider: "PUB_BLS_PAD80INyOVD3K0KJdl/7b5+UQGT0nrr8MDxO0tB80HMmaQS+X8YWRrYyyb7slAYFbOV69KN/skAFJfIFgdEEvD00MNhyaSJaJ1NGJjdKfq+OARJKoMBoBvj5/78n6BgLDpoJ7A===KEY:PVT_BLS_cvOsv1fAUDVgcK/J1j3U1DfQWMrmSFZDMiu4E0yJCEDWWZl3": {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"common.hpp","line":61,"method":"apply","hostname":"","thread_name":"nodeos","timestamp":"2024-01-09T22:46:19.780"},"format":"false: No matching suite type for ${prefix}_${data}","data":{"prefix":"BLS","data":"PAD80INyOVD3K0KJdl/7b5+UQGT0nrr8MDxO0tB80HMmaQS+X8YWRrYyyb7slAYFbOV69KN/skAFJfIFgdEEvD00MNhyaSJaJ1NGJjdKfq+OARJKoMBoBvj5/78n6BgLDpoJ7A"}}]}, ignoring!
```

### PR DESCRIPTION
**Pull request by heifner**
BLS public keys are base64 encoded which include trailing `=`. Update the `signature-provider` parsing to expect these "extra" `=`s. 
Shutdown on startup for malformed `signature-provider` arguments. Previously nodeos would log an error and continue.

Resolves #2060

### CODE REVIEW

File: plugins/signature_provider_plugin/signature_provider_plugin.cpp [hunk 1]
```diff
@@ -42,6 +42,9 @@ class signature_provider_plugin_impl {
       std::tuple<std::string, std::string, std::string> parse_spec(const std::string& spec) const {
          auto delim = spec.find("=");
          EOS_ASSERT(delim != std::string::npos, chain::plugin_config_exception, "Missing \"=\" in the key spec pair");
+         // public_key can be base64 encoded with trailing `=`
+         while( spec.size() > delim+1 && spec[delim+1] == '=' )
+            ++delim;
          auto pub_key_str = spec.substr(0, delim);
          auto spec_str = spec.substr(delim + 1);
```
Comment (linh2931) [inline plugins/signature_provider_plugin/signature_provider_plugin.cpp:49]: Will this be out of range if `=` is the last char in `spec` and `delim` points to `=`?

**Review by linh2931 — APPROVED** [review]
Later tests can be added.

File: plugins/signature_provider_plugin/signature_provider_plugin.cpp [hunk 2]
```diff
@@ -42,6 +42,9 @@ class signature_provider_plugin_impl {
       std::tuple<std::string, std::string, std::string> parse_spec(const std::string& spec) const {
          auto delim = spec.find("=");
          EOS_ASSERT(delim != std::string::npos, chain::plugin_config_exception, "Missing \"=\" in the key spec pair");
+         // public_key can be base64 encoded with trailing `=`
```
Comment (greg7mdp) [inline plugins/signature_provider_plugin/signature_provider_plugin.cpp:45]: Can you add in the comment what `spec` looks like when the public_key has trailing `=`?

File: plugins/signature_provider_plugin/signature_provider_plugin.cpp [hunk 3]
```diff
@@ -42,6 +42,11 @@ class signature_provider_plugin_impl {
...
+         // e.g. --signature-provider PUB_BLS_Fmgk<snip>iuA===KEY:PVT_BLS_NZhJ<snip>ZHFu
+         while( spec.size() > delim+1 && spec[delim+1] == '=' )
+            ++delim;
+         EOS_ASSERT(delim < spec.size() + 1, chain::plugin_config_exception, "Missing spec data in the key spec pair");
          auto pub_key_str = spec.substr(0, delim);
```
Comment (greg7mdp) [inline plugins/signature_provider_plugin/signature_provider_plugin.cpp:50]: won't `pub_key_str` potentially end with multiple `=` characters? Maybe it is not an issue?

Comment (heifner) [reply plugins/signature_provider_plugin/signature_provider_plugin.cpp:50]: Yes, which like the example comment shows is rather ugly. We will likely move to base64url in the future partly do to this.

Comment (greg7mdp) [reply plugins/signature_provider_plugin/signature_provider_plugin.cpp:50]: So should we do something like this:
```
         auto delim_end = delim;
         while( spec.size() > delim_end+1 && spec[delim_end+1] == '=' )
            ++delim_end;
         EOS_ASSERT(delim_end < spec.size() + 1, chain::plugin_config_exception, "Missing spec data in the key spec pair");
         auto pub_key_str = spec.substr(0, delim);
         auto spec_str = spec.substr(delim_end + 1);
```

Comment (heifner) [reply plugins/signature_provider_plugin/signature_provider_plugin.cpp:50]: No, The public key is `PUB_BLS_Fmgk<snip>iuA==` the separator is `=KEY:`. Also note the separator can also be `=KEOSD:` and `=SE:`.

Comment (greg7mdp) [reply plugins/signature_provider_plugin/signature_provider_plugin.cpp:50]: Oh, OK. No spaces possible, right?

**Review by greg7mdp — APPROVED** [review]

File: plugins/signature_provider_plugin/signature_provider_plugin.cpp (hunk 3 above)
Comment (heifner) [reply plugins/signature_provider_plugin/signature_provider_plugin.cpp:50]: Correct, no spaces allowed.

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: INTERNALS
summary: Better support for BLS signatures by expecting and dealing correctly with '='. In addition, nodeos will shutdown during a startup, when invalid `signature-provider` arguments are detected.  
Note: end
