### PR TITLE
Include additional info in tx_cpu_usage_exceeded exceptions

### LINKED ISSUE #330: Report more info on tx_cpu_usage_exceeded exceptions
Report in `tx_cpu_usage_exceeded` exception message if limit is do to consensus `max_transaction_cpu_usage` or transaction `max_cpu_usage_ms` or node configured `max-transaction-time` or account CPU limit along with the existing indication of subjective cpu bill amount.

### PR DESCRIPTION
**Pull request by heifner**
Include in `tx_cpu_usage_exceeded` exception message information on which trx cpu limit was hit.

Includes #562 which should be merged first.
Resolves #330

### CODE REVIEW

File: libraries/chain/transaction_context.cpp [hunk 1]
```diff
@@ -402,6 +407,26 @@ namespace eosio { namespace chain {
       }
    }
 
+   std::string transaction_context::get_tx_cpu_usage_exceeded_reason_msg(fc::microseconds& limit) const {
+      switch( tx_cpu_usage_reason ) {
+         case tx_cpu_usage_exceeded_reason::account_cpu_limit:
```
Comment (linh2931) [inline libraries/chain/transaction_context.cpp:419]: `limit` is not set for this case.

Comment (heifner) [reply libraries/chain/transaction_context.cpp:419]: That is the intention. We could report the limit, but it is redundant because that is what is hit.

```
 estimated CPU time (148164 us) is not less than the maximum billable CPU time for the transaction (146537 us) reached account cpu limit
```
It would just report `146537` as the account limit.

I could add a comment to make that clear or I could go ahead and add the redundant limit.

Comment (heifner) [reply libraries/chain/transaction_context.cpp:419]: Hmm, maybe they are all redundant:

```
transaction was executing for too long 150083us reached on chain max_transaction_cpu_usage 150000us
transaction was executing for too long 10099us reached speculative executed adjusted trx max time 10000us
transaction was executing for too long 25109us reached on chain max_transaction_cpu_usage 24999us
transaction was executing for too long 5104us reached node configured max-transaction-time 5000us
transaction was executing for too long 25068us reached node configured max-transaction-time 25000us

billed CPU time (150001 us) is greater than the maximum billable CPU time for the transaction (150000 us) reached on chain max_transaction_cpu_usage 150000us
billed CPU time (5001 us) is greater than the maximum billable CPU time for the transaction (5000 us) reached trx specified max_cpu_usage_ms 5000us
billed CPU time (131031 us) is greater than the maximum billable CPU time for the transaction (131030 us) reached account cpu limit
estimated CPU time (27900 us) is not less than the maximum billable CPU time for the transaction (27900 us) with a subjective cpu of (131818 us) reached account cpu limit
estimated CPU time (27900 us) is not less than the maximum billable CPU time for the transaction (27900 us) with a subjective cpu of (131818 us) reached account cpu limit
estimated CPU time (148164 us) is not less than the maximum billable CPU time for the transaction (146537 us) reached account cpu limit
estimated CPU time (148164 us) is not less than the maximum billable CPU time for the transaction (146537 us) reached account cpu limit
billed CPU time (138 us) is greater than the maximum billable CPU time for the transaction (0 us) reached account cpu limit
```

Comment (heifner) [reply libraries/chain/transaction_context.cpp:419]:
```
billed CPU time (150001 us) is greater than the maximum billable CPU time for the transaction (150000 us) reached on chain max_transaction_cpu_usage 150000us
billed CPU time (5001 us) is greater than the maximum billable CPU time for the transaction (5000 us) reached trx specified max_cpu_usage_ms 5000us
billed CPU time (131031 us) is greater than the maximum billable CPU time for the transaction (131030 us) reached account cpu limit 131030us
estimated CPU time (27900 us) is not less than the maximum billable CPU time for the transaction (27900 us) with a subjective cpu of (131818 us) reached account cpu limit 27900us
estimated CPU time (27900 us) is not less than the maximum billable CPU time for the transaction (27900 us) with a subjective cpu of (131818 us) reached account cpu limit 27900us
estimated CPU time (148164 us) is not less than the maximum billable CPU time for the transaction (146537 us) reached account cpu limit 146537us
estimated CPU time (148164 us) is not less than the maximum billable CPU time for the transaction (146537 us) reached account cpu limit 146537us
billed CPU time (139 us) is greater than the maximum billable CPU time for the transaction (0 us) reached account cpu limit 0us
```

**Review by linh2931 — APPROVED** [review]

File: libraries/chain/transaction_context.cpp [hunk 2]
```diff
@@ -496,28 +523,26 @@ namespace eosio { namespace chain {
...
-                           ("billed", billed_us)("billable", limit)("subjective", subjective_billed_us));           
+            auto account_limit = graylisted ? account_cpu_limit : (cpu_limited_by_account ? account_cpu_limit : objective_duration_limit.count());
+
+            if( billed_us > account_limit ) {
+               fc::microseconds tx_limit;
+               std::string assert_msg = "billed CPU time (${billed} us) is greater than the maximum";
+               assert_msg += graylisted ? " greylisted" : "";
+               assert_msg += " billable CPU time for the transaction (${billable} us)";
+               assert_msg += subjective_billed_us > 0 ? " with a subjective cpu of (${subjective} us)" : "";
+               assert_msg += get_tx_cpu_usage_exceeded_reason_msg( tx_limit );
```
Comment (greg7mdp) [inline libraries/chain/transaction_context.cpp:536]: I think I would declare the `std::string assert_msg` and do `assert_msg.reserve(1024)` to avoid a new memory allocation at each `+=` operator. Same in `validate_account_cpu_usage_estimate` below.

File: libraries/chain/transaction_context.cpp [hunk 3]
```diff
@@ -496,28 +523,26 @@ namespace eosio { namespace chain {
...
+
+               if( graylisted ) {
+                  EOS_ASSERT( false, greylist_cpu_usage_exceeded, std::move(assert_msg),
+                              ("billed", billed_us)("billable", account_limit)("subjective", subjective_billed_us)("limit", tx_limit) );
+               } else {
+                  EOS_ASSERT( false, tx_cpu_usage_exceeded, std::move(assert_msg),
+                              ("billed", billed_us)("billable", account_limit)("subjective", subjective_billed_us)("limit", tx_limit) );
```
Comment (greg7mdp) [inline libraries/chain/transaction_context.cpp:543]: Why not use `FC_THROW_EXCEPTION` instead of `EOS_ASSERT(false, ...)`. Same in `validate_account_cpu_usage_estimate` below.

File: libraries/chain/transaction_context.cpp [hunk 4]
```diff
@@ -131,6 +132,7 @@ namespace eosio { namespace chain {
          if( trx_specified_cpu_usage_limit <= objective_duration_limit ) {
             objective_duration_limit = trx_specified_cpu_usage_limit;
             billing_timer_exception_code = tx_cpu_usage_exceeded::code_value;
+            tx_cpu_usage_reason = tx_cpu_usage_exceeded_reason::user_specified_trx_max_cpu_usage_ms;
             _deadline = start + objective_duration_limit;
          }
       }
```
Comment (greg7mdp) [inline libraries/chain/transaction_context.cpp:138]: all three instances of `_deadline = start + objective_duration_limit;` could be just moved after this `if`

File: libraries/testing/include/eosio/testing/tester.hpp [hunk 5]
```diff
@@ -675,6 +675,18 @@ namespace eosio { namespace testing {
      string expected;
   };
 
+  /**
+   * Utility predicate to check whether an fc::exception message contains a given string
+   */
+  struct fc_exception_message_contains {
+     explicit fc_exception_message_contains( const string& msg )
+           : expected( msg ) {}
```
Comment (greg7mdp) [inline libraries/testing/include/eosio/testing/tester.hpp:683]: Better to do:

```
explicit fc_exception_message_contains( string msg )
           : expected( std::move(msg) ) {}
```

so that if a rvalue is passed it is moved.

File: unittests/wasm_tests.cpp [hunk 6]
```diff
@@ -1952,7 +1952,9 @@ BOOST_AUTO_TEST_CASE( billed_cpu_test ) try {
    BOOST_CHECK_LT( max_cpu_time_us + 1, cpu_limit ); // max_cpu_time_us+1 has to be less than cpu_limit to actually test max and not account
    // indicate explicit billing at max + 1
    BOOST_CHECK_EXCEPTION( push_trx( ptrx, fc::time_point::maximum(), max_cpu_time_us + 1, true, 0 ), tx_cpu_usage_exceeded,
-                          fc_exception_message_starts_with( "billed") );
+                          [](const tx_cpu_usage_exceeded& e){ fc_exception_message_starts_with starts("billed");
+                                                              fc_exception_message_contains contains("reached on chain max_transaction_cpu_usage");
+                                                              return starts(e) && contains(e); } );
```
Comment (greg7mdp) [inline unittests/wasm_tests.cpp:1957]: I probably would have written:

```
return fc_exception_message_starts_with("billed")(e) && 
       fc_exception_message_contains("reached on chain max_transaction_cpu_usage")(e);
```
but I guess it is a matter of preference.

File: libraries/chain/transaction_context.cpp (hunk 4 above)
Comment (heifner) [reply libraries/chain/transaction_context.cpp:138]: I think we should leave this as is to avoid additional diff for PR https://github.com/AntelopeIO/leap/pull/558.

File: unittests/wasm_tests.cpp (hunk 6 above)
Comment (heifner) [reply unittests/wasm_tests.cpp:1957]: This is test code and the diff in perf I don't think is worth changing it for.

File: libraries/chain/transaction_context.cpp (hunk 2 above)
Comment (heifner) [reply libraries/chain/transaction_context.cpp]: Done.

File: libraries/chain/transaction_context.cpp (hunk 3 above)
Comment (heifner) [reply libraries/chain/transaction_context.cpp]: Done.

File: libraries/testing/include/eosio/testing/tester.hpp (hunk 5 above)
Comment (heifner) [reply libraries/testing/include/eosio/testing/tester.hpp]: Done.

File: unittests/wasm_tests.cpp (hunk 6 above)
Comment (greg7mdp) [reply unittests/wasm_tests.cpp:1957]: Actually there is probably very little diff in perf , and I 100% agree it is a matter of preference.

**Review by greg7mdp — APPROVED** [review]
