### PR TITLE
[3.1] net_plugin improve block latency calculation

### LINKED ISSUE #588: net_plugin handshake storm
Observed in recent test failure logs: https://github.com/AntelopeIO/leap/actions/runs/3752991593/jobs/6375833496
```
debug 2022-12-21T21:55:32.974 net-0     net_plugin.cpp:811            operator()           ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] handle handshake_message
debug 2022-12-21T21:55:32.974 net-0     net_plugin.cpp:2766           handle_message       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] received handshake_message
debug 2022-12-21T21:55:32.974 net-0     net_plugin.cpp:2773           handle_message       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] received handshake gen 2893, lib 507, head 832
debug 2022-12-21T21:55:32.974 net-0     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] Network latency is 1ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
info  2022-12-21T21:55:32.974 net-0     net_plugin.cpp:1849           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] handshake lib 507, head 832, head id 981d8f9df4e25435.. sync 4
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:811            operator()           ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] handle handshake_message
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:2766           handle_message       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] received handshake_message
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:2773           handle_message       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] received handshake gen 2894, lib 507, head 832
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] Network latency is 1ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
info  2022-12-21T21:55:32.974 net-1     net_plugin.cpp:1849           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] handshake lib 507, head 832, head id 981d8f9df4e25435.. sync 4
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:811            operator()           ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] handle handshake_message
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:2766           handle_message       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] received handshake_message
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:2773           handle_message       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] received handshake gen 2895, lib 507, head 832
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] Network latency is 1ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
info  2022-12-21T21:55:32.974 net-1     net_plugin.cpp:1849           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 4 127.0.0.1:36386] handshake lib 507, head 832, head id 981d8f9df4e25435.. sync 4
```
Logs on the peer:
```
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:835            operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] handle notice_message
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:2990           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] received notice_message
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:3024           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] this is a catch up notice with 833 blocks
debug 2022-12-21T21:55:32.974 net-1     net_plugin.cpp:1930           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] sync_manager got catch up block notice
info  2022-12-21T21:55:32.974 net-1     net_plugin.cpp:1938           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] notice_message, pending 833, blk_num 833, id 2c240056d06a1829...
info  2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1138           operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] Sending handshake generation 2898, lib 507, head 832, id 981d8f9df4e25435
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:835            operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] handle notice_message
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:2990           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] received notice_message
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:3024           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] this is a catch up notice with 833 blocks
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1930           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] sync_manager got catch up block notice
info  2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1938           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] notice_message, pending 833, blk_num 833, id 2c240056d06a1829...
info  2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1138           operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] Sending handshake generation 2899, lib 507, head 832, id 981d8f9df4e25435
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:835            operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] handle notice_message
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:2990           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] received notice_message
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:3024           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] this is a catch up notice with 833 blocks
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1930           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] sync_manager got catch up block notice
info  2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1938           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] notice_message, pending 833, blk_num 833, id 2c240056d06a1829...
info  2022-12-21T21:55:32.974 net-2     net_plugin.cpp:1138           operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] Sending handshake generation 2900, lib 507, head 832, id 981d8f9df4e25435
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:835            operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] handle notice_message
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:2990           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] received notice_message
debug 2022-12-21T21:55:32.974 net-2     net_plugin.cpp:3024           handle_message       ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] this is a catch up notice with 833 blocks
debug 2022-12-21T21:55:32.975 net-2     net_plugin.cpp:1930           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] sync_manager got catch up block notice
info  2022-12-21T21:55:32.975 net-2     net_plugin.cpp:1938           sync_recv_notice     ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] notice_message, pending 833, blk_num 833, id 2c240056d06a1829...
info  2022-12-21T21:55:32.975 net-2     net_plugin.cpp:1138           operator()           ] ["localhost:9876 - 9379f72" - 3 127.0.0.1:9876] Sending handshake generation 2901, lib 507, head 832, id 981d8f9df4e25435
```

It looks like our network latency calculation is wrong as there should not be any block discrepancy when network latency is 0ms or 1ms. In any rate, we should not get caught in this type of loop.

### PR DESCRIPTION
**Pull request by heifner**
Remove the +1 to the block latency calculation otherwise even 0ms latency indicates 1 block latency instead of 0. The +1 makes the comparisons of `head` and `msg.head` in the `if-else` off by 1 when there is no latency. 

Added additional logging so that issues like #588 are easier to debug.

Before:
```
debug 2022-12-21T21:54:29.938 net-3     net_plugin.cpp:1790           recv_handshake       ] ["localhost:9878 - f9bdaf6" - 43 127.0.0.1:52370] Network latency is 0ms, 0 blocks discrepancy by network latency, 1 blocks discrepancy expected once message received
```

After:
```
debug 2023-01-31T00:27:27.386 net-0     net_plugin.cpp:1795           recv_handshake       ] ["localhost:9878 - 978ab39" - 1 127.0.0.1:54362] Network latency is 0ms, 0 blocks discrepancy by network latency, 0 blocks discrepancy expected once message received
```

### CODE REVIEW

File: plugins/net_plugin/net_plugin.cpp [hunk 1]
```diff
@@ -1792,8 +1792,8 @@ namespace eosio {
       }
       // number of blocks syncing node is behind from a peer node
       uint32_t nblk_behind_by_net_latency = static_cast<uint32_t>(network_latency_ns / block_interval_ns);
-      // 2x for time it takes for message to reach back to peer node, +1 to compensate for integer division truncation
-      uint32_t nblk_combined_latency = 2 * nblk_behind_by_net_latency + 1;
+      // 2x for time it takes for message to reach back to peer node
+      uint32_t nblk_combined_latency = 2 * nblk_behind_by_net_latency;
```
Comment (linh2931) [inline plugins/net_plugin/net_plugin.cpp:1796]: How about adding a check that if latency is 0, do not  +1; otherwise +1? This would keep the original intention of compensating for integer division truncation.

Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp:1796]: I think the original intention was wrong. I see no reason to round-up when the latency is multiplied by 2 anyway. I think floor is as good if not better than ceiling in this case.

**Review by linh2931 — APPROVED** [review]

**Comment by greg7mdp** [comment]
The PR title doesn't seem quite right to me.

**Comment by heifner** [comment]
> The PR title doesn't seem quite right to me.

How so?

**Comment by greg7mdp** [comment]
> How so?

Sorry if I wasn't clear. I don't find it obvious why the change reduces the amount of handshake messages. From my uninformed viewpoint, it only seem to make the message more accurate.

**Comment by heifner** [comment]
> Sorry if I wasn't clear. I don't find it obvious why the change reduces the amount of handshake messages. From my uninformed viewpoint, it only seem to make the message more accurate.

Ah, good point. I'll try to add some info about how this accomplishes the stated.

**Comment by heifner** [comment]
> Ah, good point. I'll try to add some info about how this accomplishes the stated.

I added some additional info to the PR description. @greg7mdp

**Comment by greg7mdp** [comment]
> I added some additional info to the PR description. @greg7mdp

Thanks a lot @heifner , crystal clear now :-)

**Review by dimas1185 — APPROVED** [review]

File: plugins/net_plugin/net_plugin.cpp [hunk 2]
```diff
@@ -1813,8 +1813,8 @@ namespace eosio {
       //-----------------------------
 
       if (head_id == msg.head_id) {
-         peer_ilog( c, "handshake lib ${lib}, head ${head}, head id ${id}.. sync 0",
-                    ("lib", msg.last_irreversible_block_num)("head", msg.head_num)("id", msg.head_id.str().substr(8,16)) );
+         peer_ilog( c, "handshake lib ${lib}, head ${head}, head id ${id}.. sync 0, lib ${l}",
```
Comment (greg7mdp) [inline plugins/net_plugin/net_plugin.cpp:1816]: Can we factorize these 5 `peer_ilog` as in:

```
      auto log_handshake = [&](uint32_t sync) {
         peer_ilog( c, "handshake lib ${lib}, head ${head}, head id ${id}.. sync ${sync}, head ${h}, lib ${l}",
                    ("lib", msg.last_irreversible_block_num)("head", msg.head_num)("id", msg.head_id.str().substr(8,16))
                    ("sync", sync)("h", head)("l", lib_num) );
      }

      if (head_id == msg.head_id) {
         log_handshake(0);
         c->syncing = false;
         notice_message note;
         note.known_blocks.mode = none;
         note.known_trx.mode = catch_up;
         note.known_trx.pending = 0;
         c->enqueue( note );
         return;
      }
      if (head < msg.last_irreversible_block_num) {
         log_handshake(1);
         c->syncing = false;
         if (c->sent_handshake_count > 0) {
            c->send_handshake();
         }
         return;
      }
      if (lib_num > msg.head_num + nblk_combined_latency) {
         log_handshake(2);
         if (msg.generation > 1 || c->protocol_version > proto_base) {
            notice_message note;
            note.known_trx.pending = lib_num;
            note.known_trx.mode = last_irr_catch_up;
            note.known_blocks.mode = last_irr_catch_up;
            note.known_blocks.pending = head;
            c->enqueue( note );
         }
         c->syncing = true;
         return;
      }

      if (head + nblk_combined_latency < msg.head_num ) {
         log_handshake(3);
         c->syncing = false;
         verify_catchup(c, msg.head_num, msg.head_id);
         return;
      } else if(head >= msg.head_num + nblk_combined_latency) {
         log_handshake(4);
         ...
```

**Review by greg7mdp — APPROVED** [review]

File: plugins/net_plugin/net_plugin.cpp (hunk 2 above)
Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp:1816]: I prefer not to as you lose line #.

Comment (greg7mdp) [reply plugins/net_plugin/net_plugin.cpp:1816]: fair enough! Although you could replace the lambda with a macro, as in:

```
#define log_handshake(sync) \
         peer_ilog( c, "handshake lib ${lib}, head ${head}, head id ${id}.. sync ${sync}, head ${h}, lib ${l}",\
                    ("lib", msg.last_irreversible_block_num)("head", msg.head_num)("id", msg.head_id.str().substr(8,16))\
                    ("sync", sync)("h", head)("l", lib_num) );
```

but maybe we should leave good enough alone :-).
