### PR TITLE
[4.0 -> main] Fix block time reporting log statement

### LINKED ISSUE #1360: Add producer name to trx idle log message
In debugging https://github.com/AntelopeIO/leap/issues/1349, it was observed by Kevin that it would be good to log the producer name for the following message:

```
Block #317926278 trx idle: 237us out of 199964us, success: 3, 578us, fail: 230, 197119us, transient: 0, 0us, other: 2030us
```
producer_plugin.cpp:290 in leap 4.0.3

This extra information would allow creating charts per block producer on https://blockchain.stats.eosnation.io

### LINKED ISSUE #1417: Block trx idle not being reported correctly
`Block #321172855 trx idle: 699846us out of 705689us, success: 307, 52380us, fail: 29, 17200us, transient: 0, 0us, other: -63737us` clearly something is wrong. None of these values should ever be negative.

### PR DESCRIPTION
**Pull request by heifner**
Fix issue with the tracking of block idle time.
Add producer name to the block time log statement.
Note: time logging trxs is now included in the success/fail time.

```
 Block #321409127 eosasia11111 trx idle: 253403us out of 340621us, success: 11, 11380us, fail: 10, 74407us, transient: 0, 0us, other: 1431us
```

Merges `release/4.0` into `main` including #1434 

Resolves #1360 
Resolves #1417

### CODE REVIEW

File: plugins/producer_plugin/producer_plugin.cpp [hunk 1]
```diff
@@ -232,55 +232,146 @@ class account_failures {
...
+    private:
+      block_time_tracker& _block_time_tracker;
+      time_status _time_status = time_status::fail;
+      bool _is_transient;
+   };
+
+   trx_time_tracker start_trx(bool is_transient, fc::time_point now = fc::time_point::now()) {
+      assert(!paused);
+      add_other_time(now);
+      last_time_point = now;
```
Comment (greg7mdp) [inline plugins/producer_plugin/producer_plugin.cpp:277]: this line not needed, already done in `add_other_time`.

**Review by greg7mdp — APPROVED** [review]
