### PR TITLE
Return 400 http error for unknown account

### LINKED ISSUE #591: Fix get_account fail case, RPC endpoint for is_valid_account
Use case:

Any app creating a user account must check if the account exists. 

Current solution:
Calling get_account - get_account is relatively expensive when it succeeds but assumes that the account passed in is valid.

get_account does not handle non-existing account well: It crashes with a 500 internal server error, which might be a bug and exploitable by malicious actors. 

Fixing get_account is likely also a good idea, so it fails gracefully on a non-existing account

This is a fail case trace:

```
❯ cleosm --print-request --print-response get account nnnnn       
REQUEST:
---------------------
POST /v1/chain/get_account HTTP/1.1
Host: node.hypha.earth
content-length: 29
Accept: */*
Connection: close

{
  "account_name": "nnnnn"
}
---------------------
RESPONSE:
---------------------
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 0,
    "name": "exception",
    "what": "unspecified",
    "details": [{
        "message": "unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 nnnnn)",
        "file": "http_plugin.cpp",
        "line_number": 936,
        "method": "handle_exception"
      }
    ]
  }
}
---------------------
error 2022-12-22T03:39:42.285 thread-0  main.cpp:4371                 operator()           ] Failed with error: unspecified (0)
unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 nnnnn)

```

### PR DESCRIPTION
**Pull request by heifner**
See discussion on #903 

Return a `400` http error code for unknown account instead of `500`. `400` was chosen instead of `404` because `404` is seen by `cleos` as a plugin is not enabled. `cleos` could have been modified, but to better support existing `cleos`, went with the generic `400` error code.

The following endpoints were updated to return `400` when the account could not be accessed.
`/v1/chain/get_abi`
`/v1/chain/get_code`
`/v1/chain/get_code_hash`
`/v1/chain/get_raw_code_and_abi`
`/v1/chain/get_raw_abi`
`/v1/chain/get_account`
`/v1/chain/get_table_rows`
`/v1/chain/get_currency_balance`
`/v1/chain/get_currency_stats`

```
./cleos --print-response get account test
RESPONSE:
---------------------
{
  "code": 400,
  "message": "Account lookup",
  "error": {
    "code": 3060002,
    "name": "account_query_exception",
    "what": "Account Query Exception",
    "details": [{
        "message": "unable to retrieve account info (unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 test))",
        "file": "chain_plugin.cpp",
        "line_number": 2555,
        "method": "get_account"
      }
    ]
  }
}
---------------------
Error 3060002: Account Query Exception
Most likely, the given account doesn't exist in the blockchain.
Error Details:
unable to retrieve account info (unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 test))
```

Resolves #591

### CODE REVIEW

**Review by ericpassmore — APPROVED** [review]

File: plugins/chain_plugin/chain_plugin.cpp [hunk 1]
```diff
@@ -2339,9 +2344,11 @@ read_only::get_code_hash_results read_only::get_code_hash( const get_code_hash_p
       result.code_hash = accnt.code_hash;
 
    return result;
+   } EOS_RETHROW_EXCEPTIONS(chain::account_query_exception, "unable to retrieve account code has")
```
Comment (spoonincode) [inline plugins/chain_plugin/chain_plugin.cpp:2347]: `s/has/hash/`
