### PR TITLE
Log exception details for failed transactions

### LINKED ISSUE #548: Debug error messages are not self-explanatory
```
debug 2022-12-07T11:37:49.235 nodeos    producer_plugin.cpp:237       add                  ] Failed trx, account: xxxxxxxx, reason: 3130002
```

You need to read the source code to figure out what error message means.  This is not as helpful as it could be.  Print both the error code and error message.

https://github.com/AntelopeIO/leap/blob/3041c381b706b6f57b289c51e211209293a0627e/libraries/chain/include/eosio/chain/exceptions.hpp#L470

### PR DESCRIPTION
**Pull request by heifner**
Log failed transaction exception details:

For example:
```
debug 2023-02-03T20:52:13.122 nodeos    producer_plugin.cpp:2037      push_transaction     ] Failed 3040000 trx, auth: eosio.wrap, prev billed: 0us, ran: 274us, id: 84ff2165389f800d26f5f47117ed494d30d6e4ebf797edd7ffdda80c07bcaf35, except: {"code":3040000,"name":"transaction_exception","message":"Transaction exception","stack":[{"context":{"level":"error","file":"transaction_context.cpp","line":796,"method":"validate_referenced_accounts","hostname":"","thread_name":"nodeos","timestamp":"2023-02-03T20:52:13.122"},"format":"action's authorizing actor '${account}' does not exist","data":{"account":"eosio.wrap"}}]}
```

Resolves #548

### CODE REVIEW

**Review by greg7mdp — APPROVED** [review]

File: plugins/producer_plugin/producer_plugin.cpp [hunk 1]
```diff
@@ -2023,20 +2023,20 @@ producer_plugin_impl::push_transaction( const fc::time_point& block_deadline,
...
             // this failed our configured maximum transaction time, we don't want to replay it
-            fc_dlog( _trx_failed_trace_log, "Failed ${c} trx, auth: ${a}, prev billed: ${p}us, ran: ${r}us, id: ${id}",
-                     ("c", failure_code)("a", first_auth)("p", prev_billed_cpu_time_us)
-                     ( "r", end - start )( "id", trx->id() ) );
+            fc_dlog( _trx_failed_trace_log, "Failed ${c} trx, auth: ${a}, prev billed: ${p}us, ran: ${r}us, id: ${id}, except: ${e}",
+                     ("c", e.code())("a", first_auth)("p", prev_billed_cpu_time_us)
+                     ( "r", end - start)("id", trx->id())("e", e) );
             if( !disable_subjective_enforcement )
-               _account_fails.add( first_auth, failure_code );
+               _account_fails.add( first_auth, e.code() );
```
Comment (linh2931) [inline plugins/producer_plugin/producer_plugin.cpp:2039]: `add` in `account_failures` signature was changed to `void add( const account_name& n, const fc::exception& e )`. How did this compile?

Comment (heifner) [reply plugins/producer_plugin/producer_plugin.cpp:2039]: Thanks!

Comment (heifner) [reply plugins/producer_plugin/producer_plugin.cpp]: Made the exception constructor `explicit`.

**Review by linh2931 — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]
