### PR TITLE
Set keosd max http response time to unlimited

### LINKED ISSUE #230: keosd http-max-response-time-ms setting
Users often hit the default `30ms` issue with timeouts when using `keosd` due to the default `http-max-response-time-ms` 30ms. Setting contracts or ABI can often take longer than 30ms to parse in keosd. This error is confusing to users and often hard to track down what is going wrong. Also `keosd` is meant to only be run locally and not provided as a service. 

Consider making `http-max-response-time-ms` unlimited for `keosd`.

### PR DESCRIPTION
**Pull request by heifner**
Users sometimes hit the default 30ms issue with timeouts when using `keosd` due to the default `http-max-response-time-ms` 30ms. Setting contracts or ABI can often take longer than 30ms to parse in `keosd`. This error is confusing to users and often hard to track down what is going wrong. Also `keosd` is meant to only be run locally and not provided as a service.

This PR makes `http-max-response-time-ms` unlimited for `keosd`.

Also includes a bit of cleanup around exception handling in `beast_http_session`.

Resolves #230

### CODE REVIEW

File: plugins/wallet_api_plugin/wallet_api_plugin.cpp [hunk 1]
```diff
@@ -25,7 +25,7 @@ using namespace eosio;
    [&api_handle](string, string body, url_response_callback cb) mutable { \
           try { \
              INVOKE \
-             cb(http_response_code, fc::time_point::maximum(), fc::variant(result)); \
+             cb(http_response_code, fc::time_point::now() + fc::days(365), fc::variant(result)); \
```
Comment (linh2931) [inline plugins/wallet_api_plugin/wallet_api_plugin.cpp:28]: Original 30ms can be too short, but 365 days might be too long. Do we want to set it to some reasonable number like 10 seconds so feedback can be returned in case keosd is really down?

Comment (linh2931) [reply plugins/wallet_api_plugin/wallet_api_plugin.cpp:28]: Got it.

**Review by linh2931 — APPROVED** [review]

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp [hunk 2]
```diff
@@ -159,7 +159,7 @@ class beast_http_session : public detail::abstract_conn {
             error_results results{static_cast<uint16_t>(http::status::not_found), "Not Found",
                                   error_results::error_info( fc::exception( FC_LOG_MESSAGE( error, "Unknown Endpoint" ) ),
                                                              http_plugin::verbose_errors() )};
-            send_response( fc::json::to_string( results, fc::time_point::now() + plugin_state_->max_response_time ),
+            send_response( fc::json::to_string( results, fc::time_point::maximum() ),
```
Comment (greg7mdp) [inline plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:162]: Why this change?

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp [hunk 3]
```diff
@@ -311,27 +311,33 @@ class beast_http_session : public detail::abstract_conn {
          } catch(const fc::exception& e) {
             err_str = e.to_detail_string();
             fc_elog(plugin_state_->logger, "fc::exception: ${w}", ("w", err_str));
-            error_results results{static_cast<uint16_t>(http::status::internal_server_error),
-                                  "Internal Service Error",
-                                  error_results::error_info( e, http_plugin::verbose_errors() )};
-            err_str = fc::json::to_string( results, fc::time_point::now() + plugin_state_->max_response_time );
+            if( is_send_exception_response_ ) {
```
Comment (greg7mdp) [inline plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:314]: Not related to this PR, but I don't think the name `is_send_exception_response_` is meaningful, I would prefer `should_send_exception_response_`.

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp (hunk 2 above)
Comment (heifner) [reply plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:162]: Because the input to `to_string` is small and static so no possibility of json bomb.

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp (hunk 3 above)
Comment (heifner) [reply plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:314]: We do somewhat consistently use `is` for bools, but I don't disagree.

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp [hunk 4]
```diff
@@ -311,27 +311,33 @@ class beast_http_session : public detail::abstract_conn {
...
+               error_results results{static_cast<uint16_t>(http::status::internal_server_error),
+                                     "Internal Service Error",
+                                     error_results::error_info(
+                                           fc::exception( FC_LOG_MESSAGE( error, err_str ) ),
+                                           http_plugin::verbose_errors() )};
+               err_str = fc::json::to_string( results, fc::time_point::maximum() );
+            }
          }
       } catch (fc::timeout_exception& e) {
```
[the remark this answers is not in the document]
Comment (heifner) [reply plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:342]: No because we log something diff than we return.

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp (hunk 2 above)
Comment (greg7mdp) [reply plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:162]: OK, thanks!

File: plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (heifner) [reply plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:342]: No, it will have `err_str = e.to_detail_string();` or `err_str = e.what();` or `err_str = "Unknown exception";`

[the remark this answers is not in the document]
Comment (greg7mdp) [reply plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp:342]: Oh, man I get it now, thanks for explaining!

**Review by greg7mdp — APPROVED** [review]
