### PR TITLE
[4.0] Fix possible segfault switching between read/write windows

### LINKED ISSUE #1490: Tests: fix plugin_test test failure
https://github.com/AntelopeIO/leap/actions/runs/5857836866/job/15880851171

```
failed to read response from monitor process
    {}
    plugin_test  compile_monitor.cpp:326 get_connection_to_compile_monitor

appbase: exception thrown during plugin "eosio::chain_plugin" initialization.
Miscellaneous exception
warn  2023-08-14T16:05:10.608 plugin_te test_read_only_trx.cpp:124    operator()           ] 3100000 misc_exception: Miscellaneous exception
failed to read response from monitor process
    {}
    plugin_test  compile_monitor.cpp:326 get_connection_to_compile_monitor
rethrow
    {}
    plugin_test  chain_plugin.cpp:1110 plugin_initialize
```

### PR DESCRIPTION
**Pull request by heifner**
* Always execute the lambda after pop()ing it from the queue. This is needed as the read_write queue is used to post the lambda that switches to the read window. The read window can then start and begin pushing future tasks to the read_write queue. This allows multiple threads to access the read_write at one time as the original call to switch to the read window is running unlocked, once it finishes it pops from the queue while other threads can access it. Backport of #1718 
* Fix for producer shutdown to prevent segfault and deadlock on shutdown. Backport of 1368ecd0b72f1387f0545c6deef9bd494b1aa7fe

Backport of #1718

Resolves #1490

### CODE REVIEW

File: libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp [hunk 1]
```diff
@@ -68,6 +63,19 @@ class exec_pri_queue : public boost::asio::execution_context
...
+   {
+      if( !handlers_.empty() ) {
+         auto t = pop();
+         bool empty = handlers_.empty();
+         t->execute();
+         return !empty;
+      }
+
+      return false;
+   }
```
Comment (greg7mdp) [inline libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp:77]: No need to change, but just to chat I would have written it like that.

```suggestion
   bool execute_highest()
   {
      bool empty = handlers_.empty();
      if( !empty ) {
         auto t = pop();
         empty = handlers_.empty();
         t->execute();
      }

      return !empty;
   }
```

**Review by greg7mdp — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]

File: plugins/producer_plugin/producer_plugin.cpp [hunk 2]
```diff
@@ -1389,20 +1389,13 @@ void producer_plugin::plugin_startup()
...
-     chain_plugin::handle_bad_alloc();
-   } catch(const fc::exception& e) {
-      edump((e.to_detail_string()));
-   } catch(const std::exception& e) {
-      edump((fc::std_exception_wrapper::from_current_exception(e).to_detail_string()));
-   }
-
+   boost::system::error_code ec;
+   my->_timer.cancel(ec);
+   boost::system::error_code ro_ec;
```
Comment (spoonincode) [inline plugins/producer_plugin/producer_plugin.cpp:1394]: there doesn't appear to be a need for the second `ro_ec` here

File: plugins/producer_plugin/producer_plugin.cpp [hunk 3]
```diff
@@ -1389,20 +1389,13 @@ void producer_plugin::plugin_startup()
...
+   my->_ro_timer.cancel(ro_ec);
+   app().executor().stop();
```
Comment (spoonincode) [inline plugins/producer_plugin/producer_plugin.cpp:1396]: Can you explain this line some more? In what cases would we make it here and the appbase executor would still be running?

**Review by spoonincode — APPROVED** [review]
