### PR TITLE
[4.0] fix replay for partitioned block log

### LINKED ISSUE #1136: Bug: 4.0.0GA - Replay of blocks log fails when it has been sliced using the log splitting feature
Verified in LEAP 4.0.0 GA on Ubuntu 18.04 LTS:

Steps to reproduce:
- Start with an API node that has an existing, valid blocks log that has been sliced using the stride settings.  The current blocks.log and blocks.index SHOULD NOT contain the genesis block.
- Stop the nodeos process.
- Remove the state-history, state, and protocol_features directories.
- Start the nodeos process with the --replay-blockchain option.

nodeos will fail to start replay, with the following error:

```
info  2023-05-04T18:05:40.120 nodeos    chain_plugin.cpp:730          plugin_initialize    ] Replay requested: deleting state database
warn  2023-05-04T18:05:40.120 nodeos    chain_plugin.cpp:1089         plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Genesis state is necessary to initialize fresh blockchain state but genesis state could not be found in the blocks log. Please either load from snapshot or find a blocks log that starts from genesis.
    {}
    nodeos  chain_plugin.cpp:886 plugin_initialize

error 2023-05-04T18:05:40.120 nodeos    main.cpp:161                  main                 ] 3110006 plugin_config_exception: Incorrect plugin configuration
Genesis state is necessary to initialize fresh blockchain state but genesis state could not be found in the blocks log. Please either load from snapshot or find a blocks log that starts from genesis.
    {}
    nodeos  chain_plugin.cpp:886 plugin_initialize
rethrow
    {}
    nodeos  chain_plugin.cpp:1089 plugin_initialize
```

No known workaround is available at this time.

Screenshots:
Screenshot 2023-05-04 at 10 57 16 AM

Screenshot 2023-05-04 at 10 57 54 AM

### PR DESCRIPTION
**Pull request by huangminghuang**
This PR fixes block replay problem with partitioned block log

Resolves #1136

### CODE REVIEW

**Review by heifner — CHANGES_REQUESTED** [review]

**Review by heifner — APPROVED** [review]

File: libraries/testing/tester.cpp [hunk 1]
```diff
@@ -272,11 +272,14 @@ namespace eosio { namespace testing {
       if( !expected_chain_id ) {
          expected_chain_id = controller::extract_chain_id_from_db( cfg.state_dir );
          if( !expected_chain_id ) {
-            if( fc::is_regular_file( cfg.blocks_dir / "blocks.log" ) ) {
-               expected_chain_id = block_log::extract_chain_id( cfg.blocks_dir );
-            } else {
-               expected_chain_id = genesis_state().compute_chain_id();
+            fc::path retained_dir;
+            auto paritioned_config = std::get_if<partitioned_blocklog_config>(&cfg.blog);
```
Comment (greg7mdp) [inline libraries/testing/tester.cpp:276]: s/paritioned_config/partitioned_config/
