### PR TITLE
Merge SHiP stability fixes & log splitting & memory usage improvements

### LINKED ISSUE #592: 3.2 state_history_plugin crashes under heavy load
[Information reported by community]

3.1 does not have this issue. Observed with both v3.2.0-rc1 and v3.2.0.

Reproducible by indexing with Hyperion with high scale values.

image

Double these values to speed up the indexing and will reproduce the state_history_plugin crash.

image

```
OC enabled:
##############
info  2022-12-13T16:24:31.615 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.620 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.622 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.625 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.627 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.628 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.629 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.632 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.632 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.632 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.633 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.634 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.636 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.636 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.638 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T16:24:31.643 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
double free or corruption (out)
ERROR: EOS VM OC compiler monitor exiting with active sessions


info  2022-12-13T17:11:18.060 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.062 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.068 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.068 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.068 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.069 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.069 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
Provided index out of range for variant.
    {}
    nodeos  static_variant.hpp:19 from_index
Error unpacking field trx
    {"field":"trx"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::transaction_receipt
    {"type":"eosio::chain::transaction_receipt"}
    nodeos  raw.hpp:668 unpack
Error unpacking field transactions
    {"field":"transactions"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack

warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
Provided index out of range for variant.
    {}
    nodeos  static_variant.hpp:19 from_index
Error unpacking field _storage
    {"field":"_storage"}
    nodeos  raw.hpp:363 operator()
error unpacking fc::crypto::signature
    {"type":"fc::crypto::signature"}
    nodeos  raw.hpp:668 unpack
Error unpacking field signatures
    {"field":"signatures"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::packed_transaction
    {"type":"eosio::chain::packed_transaction"}
    nodeos  raw.hpp:668 unpack
Error unpacking field trx
    {"field":"trx"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::transaction_receipt
    {"type":"eosio::chain::transaction_receipt"}
    nodeos  raw.hpp:668 unpack
Error unpacking field transactions
    {"field":"transactions"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack

info  2022-12-13T17:11:18.070 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
(b & ~1) == 0:
    {}
    nodeos  raw.hpp:334 unpack
optional<eosio::chain::legacy::producer_schedule_type>
    {"type":"eosio::chain::legacy::producer_schedule_type"}
    nodeos  raw.hpp:282 unpack
Error unpacking field new_producers
    {"field":"new_producers"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack

warn  2022-12-13T17:11:18.070 nodeos    block_log.cpp:699             read_block_by_num    ] 10 assert_exception: Assert Exception
Provided index out of range for variant.
    {}
    nodeos  static_variant.hpp:19 from_index
Error unpacking field trx
    {"field":"trx"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::transaction_receipt
    {"type":"eosio::chain::transaction_receipt"}
    nodeos  raw.hpp:668 unpack
Error unpacking field transactions
    {"field":"transactions"}
    nodeos  raw.hpp:363 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    nodeos  raw.hpp:668 unpack


OC disabled
#############
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.085 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.087 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.092 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.094 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.095 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.095 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.106 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.106 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.108 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.116 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.119 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.123 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.123 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.124 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.135 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.142 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.143 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
info  2022-12-13T17:11:18.144 nodeos    state_history_plugin.c:266    operator()           ] received get_blocks_ack_request_v0 = {"num_messages":1}
double free or corruption (out)
```

### PR DESCRIPTION
**Pull request by heifner**
Merges #638 on top of #577 & #599. Also includes some additional misc. cleanup.

Addresses the double memory used when starting from a snapshot via merge of #577.

This PR backports https://github.com/EOSIO/eos/pull/9277 and https://github.com/EOSIO/eos/pull/9821 to support supports the trace and chain state log spliting in state history plugin. 

Some new options for state history plugin are added:

- `state-history-stride`: split the state history log files when the block number is the multiple of the stride. When the stride is reached, the current history log and index will be renamed '*-history--.log/index' and a new current history log and index will be created with the most recent blocks. All files following this format will be used to construct an extended history log.
- `max-retained-history-files`: the maximum number of state history log file groups to retain so that the blocks in those files can be queried. When the number is reached, the oldest log files would be moved to archive dir or deleted if the archive dir is empty. The retained log files should not be manipulated by users.
- `state-history-retained-dir`: the location of the state history retained directory (absolute path or relative to state-history dir). 
- `state-history-archive-dir`: the location of the state history archive directory (absolute path or relative to state-history dir). If the value is empty string, log files beyond the retained limit will be deleted. All files in the archive directory are completely under user's control, i.e. they won't be accessed by nodeos anymore.

Verified this branch also fixes #592.

### CODE REVIEW

File: libraries/chain/include/eosio/chain/log_catalog.hpp [hunk 1]
```diff
@@ -0,0 +1,292 @@
+#pragma once
```
Comment (linh2931) [inline libraries/chain/include/eosio/chain/log_catalog.hpp:1]: Should those 3 log_* files belong to `libraries/state_history/include/eosio/state_history`?

File: libraries/chain/include/eosio/chain/log_catalog.hpp [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+      } else {
+         auto truncate_it = --it;
+         auto name        = truncate_it->second.filename_base;
+         bfs::rename(name.replace_extension("log"), new_name.replace_extension("log"));
+         bfs::rename(name.replace_extension("index"), new_name.replace_extension("index"));
+         std::for_each(truncate_it + 1, collection.end(), remove_files);
+         auto result = truncate_it->first;
+         collection.erase(truncate_it, collection.end());
+         return result;
+      }
```
Comment (greg7mdp) [inline libraries/chain/include/eosio/chain/log_catalog.hpp]: Should we check is `active_index` was affected?

**Comment by heifner** [comment]
Need to investigate: https://github.com/AntelopeIO/leap/actions/runs/4018367730/jobs/6903988979

File: libraries/state_history/include/eosio/state_history/log_data_base.hpp [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+   const Derived* self() const { return static_cast<const Derived*>(this); }
+
+ public:
+   using mapmode = boost::iostreams::mapped_file::mapmode;
+
+   log_data_base() = default;
+
+   void    close() { file.close(); }
+   bool    is_open() const { return file.is_open(); }
```
Comment (linh2931) [inline libraries/state_history/include/eosio/state_history/log_data_base.hpp:27]: No `open` method is provided?

File: libraries/state_history/include/eosio/state_history/types.hpp [hunk 4]
```diff
@@ -101,12 +101,16 @@ struct get_blocks_ack_request_v0 {
...
 
-struct get_blocks_result_v0 {
+struct get_blocks_result_base {
    block_position                head;
    block_position                last_irreversible;
    std::optional<block_position> this_block;
    std::optional<block_position> prev_block;
    std::optional<bytes>          block;
+};
+
```
Comment (linh2931) [inline libraries/state_history/include/eosio/state_history/types.hpp:111]: Why two empty lines?

**Review by linh2931 — COMMENTED** [review]
Should the PR title be changed to "Merge SHiP stability fixes into Main"?

**Comment by heifner** [comment]
> Should the PR title be changed to "Merge SHiP stability fixes into Main"?

Updated title and description.

File: libraries/chain/include/eosio/chain/log_catalog.hpp (hunk 1 above)
Comment (linh2931) [reply libraries/chain/include/eosio/chain/log_catalog.hpp]: Sorry, just saw those 3 files are going to be used by https://github.com/AntelopeIO/leap/pull/532 too. Then they do belong to chain include directory.

File: libraries/chain/include/eosio/chain/log_catalog.hpp [hunk 5]
```diff
@@ -59,13 +59,13 @@ struct log_catalog {
...
       if (empty())
-         return 0;
+         return std::numeric_limits<block_num_t>::max();
       return collection.begin()->first;
    }
 
    uint32_t last_block_num() const {
       if (empty())
-         return 0;
+         return std::numeric_limits<block_num_t>::max();
```
Comment (greg7mdp) [inline libraries/chain/include/eosio/chain/log_catalog.hpp:68]: I think that one should be `min()` logically.

Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/log_catalog.hpp:68]: And because the function returns `uint32_t`, it should be `std::numeric_limits<uint32_t>::min();`

File: libraries/chain/include/eosio/chain/log_catalog.hpp (hunk 2 above)
Comment (huangminghuang) [reply libraries/chain/include/eosio/chain/log_catalog.hpp:286]: active_index is now assigned in LN 270.

File: libraries/chain/include/eosio/chain/log_index.hpp [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+   }
+
+   bool is_open() const { return file.is_open(); }
+
+   using iterator = const uint64_t*;
+   iterator begin() const { return reinterpret_cast<iterator>(file.data()); }
+   iterator end() const { return reinterpret_cast<iterator>(file.data() + file.size()); }
+
+   /// @pre file.size() > 0
+   uint64_t back() const { return *(this->end() - 1); }
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/log_index.hpp:34]: Not really, it is 8 bytes either way. Also sometimes people use `&cont.back()` to get a pointer (or iterator) to the last element. Returning a value breaks this understanding. This is just a personal preference, but I think that when using APIs that look standard like `back()`, it is better to conform to the usual signature if possible.

[the remark this answers is not in the document]
Comment (huangminghuang) [reply libraries/chain/include/eosio/chain/log_index.hpp:34]: I have trouble to understand why anyone would use &back() to get a pointer to it, given the fact that 1) it is a const member, so you cannot modify it and the class doesn't even provide the front() member function so you can get the starting position of the range. It already provide begin() and end() for the said purpose. The efficiency I talked about comes from the removal of indirection, not from the size of return value.

[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/log_index.hpp:34]: What difference does it make if we indirectly access the memory inside of `back()` to return the value, or if we do that in the caller? I doubt you would see any difference.
But if you feel strongly about this, I won't insist, I don't think it is that important.

File: libraries/chain/include/eosio/chain/log_catalog.hpp (hunk 5 above)
Comment (huangminghuang) [reply libraries/chain/include/eosio/chain/log_catalog.hpp:68]: I am confused, I changed it to use max() based on your request so the line `if (collection.empty() || block_num < collection.begin()->first)` can become `if (block_num < collection.first_block_num())`. Do you want to revert that back by using `min()` instead?

File: libraries/state_history/include/eosio/state_history/log.hpp [hunk 7]
```diff
@@ -62,57 +77,265 @@ struct state_history_log_header {
...
+
+      EOS_ASSERT(file.size() >= pos + sizeof(state_history_log_header) + header.payload_size, chain::plugin_exception,
+                 "corrupt ${name}: invalid payload size for entry at position ${pos}", ("name", filename)("pos", pos));
+      return header.payload_size;
+   }
+
+   void construct_index(const fc::path& index_file_name) const {
+      fc::cfile index;
+      index.set_file_path(index_file_name);
+      index.open("w+b");
```
[the remark this answers is not in the document]
Comment (huangminghuang) [reply libraries/state_history/include/eosio/state_history/log.hpp]: open() throws exception on failure already.

File: libraries/chain/include/eosio/chain/log_catalog.hpp (hunk 5 above)
Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/log_catalog.hpp:68]: Well, I feel that the `last_block_num()` should return the smallest possible value if no blocks are present, and the `first_block_num()` should return the largest possible value if no blocks are present.

File: libraries/state_history/create_deltas.cpp [hunk 8]
```diff
@@ -73,72 +75,120 @@ std::vector<table_delta> create_deltas(const chainbase::database& db, bool full_
...
+                  chain::resource_limits::resource_limits_state_index*,
+                  chain::resource_limits::resource_limits_config_index*>());
+
+   fc::raw::pack(ds, fc::unsigned_int(num_tables));
+
+   process_table(ds, "account", db.get_index<chain::account_index>(), pack_row);
+   process_table(ds, "account_metadata", db.get_index<chain::account_metadata_index>(), pack_row);
+   process_table(ds, "code", db.get_index<chain::code_index>(), pack_row);
+
+   process_table(ds, "contract_table", db.get_index<chain::table_id_multi_index>(), pack_row);
```
[the remark this answers is not in the document]
Comment (linh2931) [reply libraries/state_history/create_deltas.cpp:166]: Sorry, I misread it as "contract_row".

File: libraries/state_history/include/eosio/state_history/log.hpp [hunk 9]
```diff
@@ -62,57 +77,265 @@ struct state_history_log_header {
...
+      EOS_ASSERT(is_ship(header.magic) && is_ship_supported_version(header.magic), chain::plugin_exception,
+                 "corrupt ${name}: invalid header for entry at position ${pos}", ("name", filename)("pos", pos));
+
+      EOS_ASSERT(file.size() >= pos + sizeof(state_history_log_header) + header.payload_size, chain::plugin_exception,
+                 "corrupt ${name}: invalid payload size for entry at position ${pos}", ("name", filename)("pos", pos));
+      return header.payload_size;
+   }
+
+   void construct_index(const fc::path& index_file_name) const {
+      fc::cfile index;
```
[the remark this answers is not in the document]
Comment (huangminghuang) [reply libraries/state_history/include/eosio/state_history/log.hpp]: renamed

**Review by linh2931 — APPROVED** [review]

File: libraries/state_history/include/eosio/state_history/log.hpp [hunk 10]
```diff
@@ -62,57 +77,262 @@ struct state_history_log_header {
...
+      if (file.is_open())
+         file.close();
+      file.set_file_path(path);
+      file.open("rb");
+      uint64_t v           = chain::read_data_at<uint64_t>(file, 0);
+      version_             = get_ship_version(v);
+      is_currently_pruned_ = is_ship_log_pruned(v);
+      file.seek_end(0);
+      size_ = file.tellp();
+      return;
```
Comment (ScottBailey) [inline libraries/state_history/include/eosio/state_history/log.hpp:187]: Superfluous `return`.

File: libraries/state_history/include/eosio/state_history/log.hpp [hunk 11]
```diff
@@ -62,57 +77,265 @@ struct state_history_log_header {
...
+        if (result == -1)
+            return -1;
+        chars_ += result;
+        return result;
+    }
+
+    template<typename Sink>
+    std::streamsize write(Sink& snk, const char_type* s, std::streamsize n)
+    {
+        std::streamsize result = bio::write(snk, s, n);
```
[the remark this answers is not in the document]
Comment (ScottBailey) [reply libraries/state_history/include/eosio/state_history/log.hpp:272]: But how does the user know that? If `chars_` is any non-zero value, then return is non-zero regardless of the result of bio::write. Maybe this should be changed to look more like `read()`?
```suggestion
        std::streamsize result = bio::write(snk, s, n);
        if (result < 0)
           return result;
```

File: libraries/state_history/include/eosio/state_history/log.hpp [hunk 12]
```diff
@@ -62,57 +77,261 @@ struct state_history_log_header {
...
+      std::get<std::unique_ptr<bio::filtering_istreambuf>>(buf)->push(bio::zlib_decompressor());
+      std::get<std::unique_ptr<bio::filtering_istreambuf>>(buf)->push(bio::restrict(bio::file_source(stream.get_file_path().string()), stream.tellp(), compressed_size));
+   }
+
+   template <typename LogData>
+   void init(LogData&& log, fc::datastream<const char*>& stream, uint64_t compressed_size) {
+      buf = std::make_unique<bio::filtering_istreambuf>();
+      std::get<std::unique_ptr<bio::filtering_istreambuf>>(buf)->push(bio::zlib_decompressor());
+      std::get<std::unique_ptr<bio::filtering_istreambuf>>(buf)->push(bio::restrict(bio::file_source(log.filename), stream.pos() - log.data(), compressed_size));
+   }
```
Comment (greg7mdp) [inline libraries/state_history/include/eosio/state_history/log.hpp:120]:
```suggestion
   template <typename StateHistoryLog>
   void init(StateHistoryLog&& log, fc::cfile& stream, uint64_t compressed_size) {
      auto istream = std::make_unique<bio::filtering_istreambuf>();
      istream->push(bio::zlib_decompressor());
      istream->push(bio::restrict(bio::file_source(stream.get_file_path().string()), stream.tellp(), compressed_size));
      buf = std::move(istream);
   }

   template <typename LogData>
   void init(LogData&& log, fc::datastream<const char*>& stream, uint64_t compressed_size) {
      auto istream = std::make_unique<bio::filtering_istreambuf>();
      istream->push(bio::zlib_decompressor());
      istream->push(bio::restrict(bio::file_source(log.filename), stream.pos() - log.data(), compressed_size));
      buf = std::move(istream);
   }
```

Just a suggestion, I think this is a little bit cleaner.

File: libraries/state_history/include/eosio/state_history/log.hpp [hunk 13]
```diff
@@ -62,57 +77,261 @@ struct state_history_log_header {
...
 
-   std::thread                                                              thr;
-   std::atomic<bool>                                                        write_thread_has_exception = false;
-   std::exception_ptr                                                       eptr;
-   boost::asio::io_context                                                  ctx;
-   boost::asio::io_context::strand                                          work_strand{ctx};
-   boost::asio::executor_work_guard<boost::asio::io_context::executor_type> work_guard =
-       boost::asio::make_work_guard(ctx);
-   std::recursive_mutex                                                     mx;
+   mutable std::mutex      _mx;
```
Comment (ScottBailey) [inline libraries/state_history/include/eosio/state_history/log.hpp:292]: Strictly speaking, this is not a required change; however, it would be nice if we documented the member data and/or functions that NEEDED mutex protection.

File: libraries/chain/include/eosio/chain/log_index.hpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (ScottBailey) [reply libraries/chain/include/eosio/chain/log_index.hpp]: I believe Greg's point was a pattern expectation - he expects this to follow the pattern set out in std containers. I agree with him, I think it's better to follow that pattern when we can; however, I also agree that it's just not that important.

File: libraries/state_history/include/eosio/state_history/log.hpp (hunk 13 above)
Comment (ScottBailey) [reply libraries/state_history/include/eosio/state_history/log.hpp]: Thanks!

File: libraries/state_history/include/eosio/state_history/log.hpp (hunk 12 above)
Comment (greg7mdp) [reply libraries/state_history/include/eosio/state_history/log.hpp]: Thanks!

File: plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp [hunk 14]
```diff
@@ -0,0 +1,478 @@
...
+         auto& optional_log = plugin->get_chain_state_log();
+         if( optional_log ) {
+            buf.emplace( optional_log->create_locked_decompress_stream() );
+            return optional_log->get_unpacked_entry( result.this_block->block_num, *buf );
+         }
+      }
+      return 0;
+   }
+
+   using result_type = void;
```
Comment (ScottBailey) [inline plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp:298]: I didn't find where this is used?

File: libraries/state_history/include/eosio/state_history/log.hpp (hunk 13 above)
Comment (heifner) [reply libraries/state_history/include/eosio/state_history/log.hpp]: Your welcome.

File: libraries/state_history/include/eosio/state_history/log.hpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (ScottBailey) [reply libraries/state_history/include/eosio/state_history/log.hpp]: Rename confirmed.

**Review by ScottBailey — CHANGES_REQUESTED** [review]
Please address comments in:
- libraries/chain/include/eosio/chain/log_catalog.hpp
- plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp

Thanks!

File: libraries/chain/include/eosio/chain/log_index.hpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (huangminghuang) [reply libraries/chain/include/eosio/chain/log_index.hpp]: The code has reimplemented with file I/O instead memory file I/O when greg looked at it based on the request of Matt. The new implementation just returns a value directly read from file which doesn't mapped to a persistent memory address as before. Return a reference for current implementation with result in undefined behavior

File: plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp (hunk 14 above)
Comment (heifner) [reply plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp]: Removed

File: libraries/state_history/include/eosio/state_history/log.hpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (ScottBailey) [reply libraries/state_history/include/eosio/state_history/log.hpp:273]: Matches boost 1.81.0, satisfied.

**Review by ScottBailey — APPROVED** [review]
lgtm, thanks!
