### PR TITLE
Move log line for `onblock` and update saved log file for tests

### LINKED ISSUE #1067: deep mind logging of onblock
Currently `onblock` `TRX_OP CREATE onblock ${id} ${trx}` is logged for `onblock` transactions that could fail as it is logged at the creation of the `onblock` and doesn't verify the `onblock` does not fail before reporting it.

### PR DESCRIPTION
**Pull request by greg7mdp**
Resolves #1067

### CODE REVIEW

File: libraries/chain/controller.cpp [hunk 1]
```diff
@@ -402,11 +402,13 @@ struct controller_impl {
       }
    }
 
-   void dmlog_applied_transaction(const transaction_trace_ptr& t) {
+   void dmlog_applied_transaction(const transaction_trace_ptr& t, const signed_transaction *trx = nullptr) {
       // dmlog_applied_transaction is called by push_scheduled_transaction
       // where transient transactions are not possible, and by push_transaction
       // only when the transaction is not transient
       if (auto dm_logger = get_deep_mind_logger(false)) {
+         if (trx && !trx->actions.empty() && trx->actions[0].name == "onblock"_n)
```
Comment (heifner) [inline libraries/chain/controller.cpp:410]: Use `trace.cpp` `is_onblock`. No need to pass in the `signed_transaction`.
BTW, you would want to use `get_transaction()` of `packed_transaction` not `get_signed_transaction()`.

**Review by heifner — CHANGES_REQUESTED** [review]

File: libraries/chain/controller.cpp (hunk 1 above)
Comment (greg7mdp) [reply libraries/chain/controller.cpp:410]: Hum, should I also rewrite `dm_logger->on_onblock()` to take a transaction_trace?

Comment (heifner) [reply libraries/chain/controller.cpp:410]: Yes, probably better than doing the `get<packed_transaction>(t.receipt.trx).get_signed_transaction()` with appropriate error checking. Also I missed that `on_onblock` was packing a `signed_transaction`, so ignore my comment about `get_transaction` vs `get_signed_transaction` as signed transaction is desired here apparently.

Comment (greg7mdp) [reply libraries/chain/controller.cpp:410]: Would that be better than passing the `signed_transaction` like today, but using `is_onblock` as you suggested?

Comment (greg7mdp) [reply libraries/chain/controller.cpp:410]: `t.receipt` is just a `transaction_receipt_header`, not a `transaction_receipt`, so it doesn't have the `trx` member.

Comment (heifner) [reply libraries/chain/controller.cpp:410]: ugh, so it is.

Comment (greg7mdp) [reply libraries/chain/controller.cpp:410]: What about using `is_onblock()` like this? Or leave as is?

```
   void dmlog_applied_transaction(const transaction_trace_ptr& t, const signed_transaction *trx = nullptr) {
      // dmlog_applied_transaction is called by push_scheduled_transaction
      // where transient transactions are not possible, and by push_transaction
      // only when the transaction is not transient
      if (auto dm_logger = get_deep_mind_logger(false)) {
         if (is_onblock(*t))
            dm_logger->on_onblock(*trx);
         dm_logger->on_applied_transaction(self.head_block_num() + 1, t);
      }
   }
```

Comment (heifner) [reply libraries/chain/controller.cpp:410]: Yes. `const signed_transaction* trx = nullptr`. Should probably check for or assert trx != nullptr.

File: libraries/chain/controller.cpp [hunk 2]
```diff
@@ -1627,7 +1629,7 @@ struct controller_impl {
                        emit(self.accepted_transaction, trx);
                    }
 
-                   dmlog_applied_transaction(trace);
+                   dmlog_applied_transaction(trace, &trx->packed_trx()->get_signed_transaction());
```
Comment (heifner) [inline libraries/chain/controller.cpp:1632]: `trn`

Comment (greg7mdp) [reply libraries/chain/controller.cpp:1632]: I don't understand what you mean?

Comment (heifner) [reply libraries/chain/controller.cpp:1632]: There is already the `trn` variable which is the `signed_transaction` in scope.

Comment (greg7mdp) [reply libraries/chain/controller.cpp]: done, thank you Kevin!

**Comment by greg7mdp** [comment]
Oops, this needs to go to 4.0 branch. I'll create another PR.

**Review by heifner — APPROVED** [review]

File: libraries/chain/controller.cpp [hunk 3]
```diff
@@ -402,11 +402,13 @@ struct controller_impl {
       }
    }
 
-   void dmlog_applied_transaction(const transaction_trace_ptr& t) {
+   void dmlog_applied_transaction(const transaction_trace_ptr& t, const signed_transaction *trx = nullptr) {
```
Comment (linh2931) [inline libraries/chain/controller.cpp:405]: Not a big deal, can `const signed_transaction *trx` be changed to `const signed_transaction* trx` to be consistent with existing style?

Better yet, not make this as a default argument. We try to avoid default arguments unless plain arguments cause big changes, so we know every calling place has been looked at.

Comment (greg7mdp) [reply libraries/chain/controller.cpp]: Actually, I was trying to keep the changes minimal, otherwise I have to add `nullptr` to the six other call locations, but I'm ok doing it if you think it is preferable.

Comment (greg7mdp) [reply libraries/chain/controller.cpp]: I did the whitespace update btw.
