### PR TITLE
[4.0 -> main] Fix incorrect serializing of std::optional when value is not provided - (GH #1189)

### LINKED ISSUE #1189: abi_serializer: Missing field exception thrown when an std::optional is used in a field of an action input parameter
```
struct test_input {
   uint64_t a;
   std::optional<uint64_t> b;
};

[[eosio::action]] void test(const test_input& input);
```

Create a failing test case reproducing this issue. Then fix it.

### PR DESCRIPTION
**Pull request by greg7mdp**
Resolves #1189 .

When serializing a std::optional field, and a value is not provided for the std::optional, we need to add into the serialization the flag specifying that a missing value is serialized. Prior to this PR, the flag was missing.

### CODE REVIEW

File: unittests/abi_tests.cpp [hunk 1]
```diff
@@ -41,7 +41,17 @@ FC_REFLECT(act_sig, (sig) )
...
+#ifdef NDEBUG
 fc::microseconds max_serialization_time = fc::seconds(1); // some test machines are very slow
+#else
+fc::microseconds max_serialization_time = fc::microseconds::maximum(); // don't check in debug builds
+#endif
+
+static fc::time_point get_deadline() {
+   if (max_serialization_time == fc::microseconds::maximum())
+      return fc::time_point(fc::microseconds::maximum());
+   return fc::time_point::now() + max_serialization_time;
```
Comment (heifner) [inline unittests/abi_tests.cpp:53]: You can use `safe_add` in `main`.

**Review by heifner — APPROVED** [review]

File: unittests/abi_tests.cpp (hunk 1 above)
Comment (greg7mdp) [reply unittests/abi_tests.cpp:53]: Thanks. I also did a small cleanup in `safe_add()`

**Review by heifner — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]
