### PR TITLE
IF: Support irreversible read-mode under Savanna

### LINKED ISSUE #2286: IF: Support irreversible read-mode under Savanna
Depends on #2057.

Currently `--read-mode irreversible` does not work in instant finality mode.

```
info  2024-03-06T15:06:06.458 nodeos    producer_plugin.cpp:757       on_incoming_block    ] Received block 95af53bc64d04208... #123 @ 2024-03-06T15:06:06.500 signed by eosio [trxs: 1, lib: 122, net: 0, cpu: 0, elapsed: 0, time: 0, latency: -41 ms]
debug 2024-03-06T15:06:06.458 nodeos    net_plugin.cpp:3243           update_chain_info    ] updating chain info lib 122, fork 123
debug 2024-03-06T15:06:06.458 net-0     net_plugin.cpp:3883           operator()           ] accepted signed_block : #123 95af53bc64d04208...
debug 2024-03-06T15:06:06.889 net-2     net_plugin.cpp:3112           process_next_block_m ] ["localhost:9776:blk - b741d54" - 1 127.0.0.1:9776] received block 124, id 4ad5dddb65b2253e..., latency: -110ms, head 123
debug 2024-03-06T15:06:06.889 net-2     net_plugin.cpp:3761           handle_message       ] ["localhost:9776:blk - b741d54" - 1 127.0.0.1:9776] posting block 124 to dispatcher strand
info  2024-03-06T15:06:06.889 net-2     net_plugin.cpp:3788           operator()           ] bad block exception connection 1: #124 4ad5dddb65b2253e...: Block is not signed with expected key (3030008)
block signed by unexpected key
```

### PR DESCRIPTION
**Pull request by heifner**
Add support for transition to savanna running with `read-mode = irreversible`.

Resolves #2286

### CODE REVIEW

File: libraries/chain/controller.cpp [hunk 1]
```diff
@@ -1246,14 +1246,49 @@ struct controller_impl {
       }
    }
 
+   template<typename ForkDB, typename BSP>
+   void apply_irreversible_block(ForkDB& forkdb, const BSP& bsp) {
+      if( read_mode == db_read_mode::IRREVERSIBLE ) {
```
Comment (linh2931) [inline libraries/chain/controller.cpp:1251]: You can do a `if( read_mode != db_read_mode::IRREVERSIBLE ) return;` to avoid one level of nesting. But this is minor.

File: libraries/chain/controller.cpp [hunk 2]
```diff
@@ -1246,14 +1246,49 @@ struct controller_impl {
...
+               }
+               apply_block(br, bsp, controller::block_status::complete, trx_meta_cache_lookup{});
+            } else {
+               // only called during transition when not a proper savanna block
+               fork_db.apply_l<void>([&](const auto& forkdb_l) {
+                  block_state_legacy_ptr legacy = forkdb_l.get_block(bsp->id());
+                  fork_db.switch_to_legacy(); // apply block uses to know what types to create
+                  fc::scoped_exit<std::function<void()>> e([&]{fork_db.switch_to_both();});
+                  apply_block(br, legacy, controller::block_status::complete, trx_meta_cache_lookup{});
+                  // irreversible apply was just done, calculate new_valid here instead of in transition_to_savanna()
```
Comment (linh2931) [inline libraries/chain/controller.cpp:1270]: Is it possible to create `valid` in one place in `transition_to_savanna()`?

File: tests/transition_to_if.py [hunk 3]
```diff
@@ -63,7 +64,9 @@
     assert cluster.biosNode.waitForLibToAdvance(), "Lib should advance after instant finality activated"
     assert cluster.biosNode.waitForProducer("defproducera"), "Did not see defproducera"
     assert cluster.biosNode.waitForHeadToAdvance(blocksToAdvance=13) # into next producer
```
Comment (linh2931) [inline tests/transition_to_if.py:66]: Not from your PR. You can add an error message like head not reached 13 on biosNode.

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: INTERNALS
summary: Add support for transition to savanna running with read-mode = irreversible.
Note:end

File: libraries/chain/controller.cpp (hunk 2 above)
Comment (heifner) [reply libraries/chain/controller.cpp]: Factored out into a function.

File: tests/transition_to_if.py (hunk 3 above)
Comment (heifner) [reply tests/transition_to_if.py]: Done

File: libraries/chain/controller.cpp [hunk 4]
```diff
@@ -1246,14 +1246,63 @@ struct controller_impl {
...
+         apply_block(br, bsp, controller::block_status::complete, trx_meta_cache_lookup{});
+      } else {
+         assert(bsp->block);
+         if (bsp->block->is_proper_svnn_block()) {
+            // if chain_head is legacy, update to non-legacy chain_head, this is needed so that the correct block_state is created in apply_block
+            if (std::holds_alternative<block_state_legacy_ptr>(chain_head.internal())) {
+               auto prev = forkdb.get_block(bsp->previous(), include_root_t::yes);
+               assert(prev);
+               chain_head = block_handle{prev};
+            }
```
Comment (greg7mdp) [inline libraries/chain/controller.cpp:1265]: Why not `apply_l` instead of `holds_alternative`?

File: libraries/chain/fork_database.cpp [hunk 5]
```diff
@@ -804,6 +804,16 @@ namespace eosio::chain {
...
 
+   // only called from the main thread
+   void fork_database::switch_to_legacy() {
+      in_use = in_use_t::legacy;
+   }
+
+   // only called from the main thread
+   void fork_database::switch_to_both() {
+      in_use = in_use_t::both;
+   }
```
Comment (greg7mdp) [inline libraries/chain/fork_database.cpp:815]: What about a single function: `fork_database::switch_to(in_use_t v);`?

I'd add this to controller_impl: `using in_use_t = fork_database::in_use_t;`

File: libraries/chain/controller.cpp [hunk 6]
```diff
@@ -1246,14 +1246,63 @@ struct controller_impl {
...
+         } else {
+            // only called during transition when not a proper savanna block
+            fork_db.apply_l<void>([&](const auto& forkdb_l) {
+               block_state_legacy_ptr legacy = forkdb_l.get_block(bsp->id());
+               fork_db.switch_to_legacy(); // apply block uses to know what types to create
+               fc::scoped_exit<std::function<void()>> e([&]{fork_db.switch_to_both();});
+               apply_block(br, legacy, controller::block_status::complete, trx_meta_cache_lookup{});
+               // irreversible apply was just done, calculate new_valid here instead of in transition_to_savanna()
+               assert(legacy->action_receipt_digests);
+               auto prev = forkdb.get_block(legacy->previous(), include_root_t::yes);
```
Comment (greg7mdp) [inline libraries/chain/controller.cpp:1276]: you could use `fork_db_l` here, right?

File: libraries/chain/controller.cpp [hunk 7]
```diff
@@ -1246,14 +1246,63 @@ struct controller_impl {
...
+
    void transition_to_savanna() {
       assert(chain_head.header().contains_header_extension(instant_finality_extension::extension_id()));
       // copy head branch branch from legacy forkdb legacy to savanna forkdb
       fork_database_legacy_t::branch_t legacy_branch;
       block_state_legacy_ptr legacy_root;
       fork_db.apply_l<void>([&](const auto& forkdb) {
          legacy_root = forkdb.root();
-         legacy_branch = forkdb.fetch_branch(forkdb.head()->id());
+         legacy_branch = forkdb.fetch_branch(fork_db_head(forkdb, irreversible_mode())->id());
```
Comment (greg7mdp) [inline libraries/chain/controller.cpp:1305]: Every time we call `fork_db_head` we pass `irreversible_mode())`, so why not just call `irreversible_mode())` inside `fork_db_head` instead of passing an extra parameter.

File: libraries/chain/fork_database.cpp (hunk 5 above)
Comment (heifner) [reply libraries/chain/fork_database.cpp:815]: Originally didn't need all three. At this point, might as well.

File: libraries/chain/controller.cpp (hunk 6 above)
Comment (heifner) [reply libraries/chain/controller.cpp:1276]: No, we need `fork_db_s` because `prev` needs to be a `block_state_ptr`.

File: libraries/chain/controller.cpp (hunk 7 above)
Comment (heifner) [reply libraries/chain/controller.cpp:1305]: I think it makes it more obvious. If `fork_db_head()` sometimes returns `fork_db` `pending_head()`, seems like that could really confuse someone. I would expect `fork_db_head()` to be simply `return fork_db->head()`.

File: libraries/chain/controller.cpp (hunk 6 above)
Comment (greg7mdp) [reply libraries/chain/controller.cpp]: I didn't think it would return a  `block_state_ptr` because we just did `fork_db.switch_to(fork_database::in_use_t::legacy);`?

File: libraries/chain/controller.cpp (hunk 7 above)
Comment (greg7mdp) [reply libraries/chain/controller.cpp:1305]: I'm not sure that it is beneficial to add redundency to be more explicit. 
Maybe we could use another function name `fork_db_head_or_pending_head()`?

File: libraries/chain/controller.cpp (hunk 6 above)
Comment (heifner) [reply libraries/chain/controller.cpp]: `forkdb` here is the passed in `forkdb`. Not the `forkdb_l` from the lambda argument.

**Review by greg7mdp — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]
