### PR TITLE
Subjectively bill for failed transactions during block production

### LINKED ISSUE #551: Subjectively bill for failed trxs during block production
Currently subjective CPU billing is disabled during block production. The idea being that objective CPU should be applied during block production.

Recommend subjectively billing for failed transactions during block production since we have no objective billing for failed transactions.

### PR DESCRIPTION
**Pull request by heifner**
Subjectively bill for failed transactions during block production since failed transaction time not part of objective account cpu billing.
Includes removal of dead-code in `subjective_billing` that should have been removed as part of #414.

Resolves #551 
Related #414

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]

File: plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp [hunk 1]
```diff
@@ -59,7 +59,6 @@ class subjective_billing {
    bool                                      _disabled = false;
    trx_cache_index                           _trx_cache_index;
    account_subjective_bill_cache             _account_subjective_bill_cache;
-   block_subjective_bill_cache               _block_subjective_bill_cache;
```
Comment (greg7mdp) [inline plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp:62]: Should also remove the `using block_subjective_bill_cache = std::map<account_name, uint64_t>;` 5 lines above.

Comment (heifner) [reply plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp:62]: Done. Also made some other minor cleanup changes.

File: plugins/producer_plugin/producer_plugin.cpp [hunk 2]
```diff
@@ -2052,10 +2049,9 @@ producer_plugin_impl::push_transaction( const fc::time_point& block_deadline,
                ("a",first_auth)("b",sub_bill)("t",trace->elapsed)("r", end - start));
       _account_fails.add_success_time(end - start);
       log_trx_results( trx, trace, start );
-      // if producing then trx is in the pending block and not immediately reverted
-      if (!disable_subjective_billing) {
-         _subjective_billing.subjective_bill( trx->id(), trx->packed_trx()->expiration(), first_auth, trace->elapsed,
-                                              _pending_block_mode == pending_block_mode::producing );
+      // if producing then trx is in objective cpu account billing
+      if (!disable_subjective_enforcement && _pending_block_mode != pending_block_mode::producing) {
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply plugins/producer_plugin/producer_plugin.cpp:2053]: OK, I see that the logic didn't change for this test.

**Review by greg7mdp — APPROVED** [review]
